### ISSUE TITLE
GKE Ingress requires pathType to be ImplementationSpecific

### ISSUE THREAD

**Issue by tvories** [hashicorp/consul-helm#1011]
### Overview of the Issue

In a GKE cluster, when attempting to use GKE ingress, we are receiving an error:

`4m          Warning   Translate          ingress/consul-consul-ingress                     Translation failed: invalid ingress spec: only "ImplementationSpecific" path type is supported`

[According to Google](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress), for ingress to work properly, `pathType` needs to be set to `ImplementationSpecific`.  In the `ui-ingress.yaml` template, the value is hardcoded to `prefix`.

### Reproduction Steps

1. When running helm install with the following `values.yml`:
```
ui:
      ingress:
        annotations: | # https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#ingress_annotations
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: ${google_compute_global_address.consul.name}
          networking.gke.io/v1beta1.FrontendConfig: ${helm_release.consul_gcp_ingress_configs.name}
        enabled: true
        hosts:
          - host: ${trimsuffix(google_dns_record_set.consul.name, ".")}
            paths:
              - /* # Google wants /* instead of /
        tls:
          - hosts:
            - consul.example.com
            secretName: ${kubernetes_secret.consul_pki.metadata.0.name}

```
1. View error

`4m          Warning   Translate          ingress/consul-consul-ingress                     Translation failed: invalid ingress spec: only "ImplementationSpecific" path type is supported`

### Expected behavior

Values.yaml should allow someone to override default `pathType` to whichever type they need.

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: 1.19.10-gke.1600
- `consul-helm` version: 0.31.1

Additionally, please provide details regarding the Kubernetes Infrastructure, if known:
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): GKE
