### ISSUE TITLE
0.32.1/1.10.0 WAN Federation consul-server-acl-init job failing to execute resulting in failed helm installation

### ISSUE THREAD

**Issue by shellfu** [hashicorp/consul-helm#1039]
### Overview of the Issue

Installation of Primary datacenter went well and by the book and was installed with the following chart
CHART: consul-0.32.1
CONSUL: 1.10.0

Installation of Secondary datacenter failed to execute the `consul-server-acl-init` job in the secondary datacenter with federation enabled. 
CHART: consul-0.32.1
CONSUL: 1.10.0

### Reproduction Steps

**1. Installation of Consul in the Primary DC**

`helm install consul -n consul -f $BELOW_VALUES hashicorp/consul --set global.name=consul`

```yaml
client:
  enabled: true
  grpc: true
connectInject:
  aclBindingRuleSelector: serviceaccount.name!=default
  default: false
  enabled: true
  metrics:
    defaultEnableMerging: true
    defaultEnabled: true
    defaultMergedMetricsPort: 20100
    defaultPrometheusScrapePath: /metrics
    defaultPrometheusScrapePort: 20200
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
controller:
  enabled: true
dns:
  enabled: true
global:
  acls:
    createReplicationToken: true
    manageSystemACLs: true
  datacenter: primary
  enabled: true
  federation:
    createFederationSecret: true
    enabled: true
  gossipEncryption:
    secretKey: key
    secretName: consul-gossip-encryption-key
  image: hashicorp/consul:1.10.0
  imageEnvoy: envoyproxy/envoy-alpine:v1.18.3
  imageK8S: hashicorp/consul-k8s:0.26.0
  logJSON: true
  metrics:
    agentMetricsRetentionTime: 1m
    enableAgentMetrics: false
    enableGatewayMetrics: true
    enabled: true
  name: consul
  tls:
    enableAutoEncrypt: true
    enabled: true
    httpsOnly: true
    serverAdditionalDNSSANs:
    - '*.consul'
    - '*.svc.cluster.local'
    - '*.de.example.net'
    verify: false
meshGateway:
  enabled: true
  service:
    enabled: true
    port: 443
    type: LoadBalancer
  wanAddress:
    port: 443
    source: Service
server:
  bootstrapExpect: 5
  connect: true
  disruptionBudget:
    enabled: true
    maxUnavailable: 2
  enabled: true
  extraConfig: |
    {
      "primary_datacenter": "primary",
      "performance": {
        "raft_multiplier": 3
      },
      "dns_config": {
        "allow_stale": true,
        "cache_max_age": "10s",
        "enable_additional_node_meta_txt": false,
        "node_ttl": "1m",
        "soa": {
          "expire": 86400,
          "min_ttl": 30,
          "refresh": 3600,
          "retry": 600
        },
        "use_cache": true
      },
      "telemetry": {
        "prometheus_retention_time": "30s",
        "dogstatsd_addr": "localhost:8125",
        "disable_hostname": true
      },
      "ui_config": {
        "dashboard_url_templates": {
          "service": "https://grafana-1.monitoring.example.net:3000/d/lDlaj-NGz/service-overview?orgId=1&var-service={{ "{{" }}Service.Name}}&var-namespace={{ "{{" }}Service.Namespace}}&var-dc={{ "{{" }}Datacenter}}"
        }
      }
    }
  replicas: 5
  resources:
    limits:
      cpu: 500m
      memory: 10Gi
    requests:
      cpu: 500m
      memory: 10Gi
  storage: 10Gi
syncCatalog:
  default: true
  enabled: true
  nodePortSyncType: ExternalFirst
  syncClusterIPServices: true
  toConsul: true
  toK8S: true
ui:
  enabled: true
  metrics:
    baseURL: "http://mon-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    enabled: true
    provider: prometheus
  service:
    enabled: true
    type: NodePort

```

**2. Create the Proxy Default in Primary**

`kubectl apply -n consul -f $BELOW_YAML`

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    envoy_prometheus_bind_addr: 0.0.0.0:9102
    protocol: http
  meshGateway: 
    mode: 'local'
```

**3. Export `consul-federation` from Primary and Import to Secondary**
`kubectl get secret -n consul consul-federation -oyaml > secret.consul-federation.yaml`
`kucbectl config use-context secondary`
`kubectl apply -n consul -f secret.consul-federation.yaml`

**4. Installation of Consul in Secondary DC**

`helm install consul -n consul -f $BELOW_VALUES hashicorp/consul --set global.name=consul`

```yaml
client:
  enabled: true
  grpc: true
connectInject:
  aclBindingRuleSelector: serviceaccount.name!=default
  default: false
  enabled: true
  metrics:
    defaultEnableMerging: true
    defaultEnabled: true
    defaultMergedMetricsPort: 20100
    defaultPrometheusScrapePath: /metrics
    defaultPrometheusScrapePort: 20200
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
controller:
  enabled: true
dns:
  enabled: true
global:
  acls:
    manageSystemACLs: true
    replicationToken:
      secretKey: replicationToken
      secretName: consul-federation
  datacenter: secondary
  enabled: true
  federation:
    enabled: true
  gossipEncryption:
    secretKey: gossipEncryptionKey
    secretName: consul-federation
  image: hashicorp/consul:1.10.0
  imageEnvoy: envoyproxy/envoy-alpine:v1.18.3
  imageK8S: hashicorp/consul-k8s:0.26.0
  logJSON: true
  metrics:
    agentMetricsRetentionTime: 1m
    enableAgentMetrics: false
    enableGatewayMetrics: true
    enabled: true
  name: consul
  tls:
    caCert:
      secretKey: caCert
      secretName: consul-federation
    caKey:
      secretKey: caKey
      secretName: consul-federation
    enableAutoEncrypt: true
    enabled: true
    httpsOnly: true
    serverAdditionalDNSSANs:
    - '*.consul'
    - '*.svc.cluster.local'
    - '*.de.example.net'
    verify: false
meshGateway:
  enabled: true
  service:
    enabled: true
    port: 443
    type: LoadBalancer
  wanAddress:
    port: 443
    source: Service
server:
  bootstrapExpect: 5
  connect: true
  disruptionBudget:
    enabled: true
    maxUnavailable: 2
  enabled: true
  # Here we're including the server config exported from the primary
  # via the federation secret. This config includes the addresses of
  # the primary datacenter's mesh gateways so Consul can begin federation.
  extraVolumes:
    - type: secret
      name: consul-federation
      items:
        - key: serverConfigJSON
          path: config.json
      load: true
  extraConfig: |
    {
      "primary_datacenter": "primary",
      "performance": {
        "raft_multiplier": 3
      },
      "dns_config": {
        "allow_stale": true,
        "cache_max_age": "10s",
        "enable_additional_node_meta_txt": false,
        "node_ttl": "1m",
        "soa": {
          "expire": 86400,
          "min_ttl": 30,
          "refresh": 3600,
          "retry": 600
        },
        "use_cache": true
      },
      "telemetry": {
        "prometheus_retention_time": "30s",
        "dogstatsd_addr": "localhost:8125",
        "disable_hostname": true
      },
      "ui_config": {
        "dashboard_url_templates": {
          "service": "https://grafana-1.monitoring.example.net:3000/d/lDlaj-NGz/service-overview?orgId=1&var-service={{ "{{" }}Service.Name}}&var-namespace={{ "{{" }}Service.Namespace}}&var-dc={{ "{{" }}Datacenter}}"
        }
      }
    }
  replicas: 5
  resources:
    limits:
      cpu: 500m
      memory: 10Gi
    requests:
      cpu: 500m
      memory: 10Gi
  storage: 10Gi
syncCatalog:
  default: true
  enabled: true
  nodePortSyncType: ExternalFirst
  syncClusterIPServices: true
  toConsul: true
  toK8S: true
ui:
  enabled: true
  metrics:
    baseURL: "http://mon-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    enabled: true
    provider: prometheus
  service:
    enabled: true
    type: NodePort
```

### Expected behavior

I expect the secondary datacenter to come online but federated with the primary.

### Environment details
- `consul-k8s` version: 0.26.0
- `consul-helm` version: 0.32.1
- `values.yaml` used to deploy the helm chart: above for both primary and secondary

### Additional Context
`kubectl get pods -n consul`
```
$ kubectl get pods -n consul
NAME                                                        READY   STATUS     RESTARTS   AGE
consul-872wq                                                0/1     Init:0/1   0          34m
consul-connect-injector-webhook-deployment-8cf76674-cks2h   0/1     Init:0/2   0          34m
consul-connect-injector-webhook-deployment-8cf76674-pm6sp   0/1     Init:0/2   0          34m
consul-controller-6d998c67c8-f958f                          0/1     Init:0/2   0          34m
consul-lc78g                                                0/1     Init:0/1   0          34m
consul-mesh-gateway-8544494849-mhcpd                        0/2     Init:1/3   0          34m
consul-mesh-gateway-8544494849-tv46x                        0/2     Init:1/3   0          34m
consul-mvggh                                                0/1     Init:0/1   0          34m
consul-r797z                                                0/1     Init:0/1   0          34m
consul-server-0                                             1/1     Running    0          34m
consul-server-1                                             1/1     Running    0          34m
consul-server-2                                             1/1     Running    0          34m
consul-server-3                                             1/1     Running    0          34m
consul-server-4                                             1/1     Running    0          34m
consul-server-acl-init-2k4z8                                1/1     Running    0          9m28s
consul-server-acl-init-4wrtt                                0/1     Error      0          19m
consul-server-acl-init-9sf76                                0/1     Error      0          29m
consul-sync-catalog-7cdc945454-b96tn                        0/1     Init:0/2   0          34m
consul-vb9zv                                                0/1     Init:0/1   0          34m
consul-vnx4t                                                0/1     Init:0/1   0          34m
consul-webhook-cert-manager-66bc8fb64f-wrmq5                1/1     Running    0          34m
```

Additionally, you can view the logs from the acl init job *after* the servers successfully came online.

`kubectl logs -n consul consul-server-acl-init-2k4z8`

```
2021-07-15T18:59:35.664Z [INFO]  ACL replication is enabled so skipping Consul server ACL bootstrapping
2021-07-15T18:59:36.069Z [ERROR] Failure: calling /agent/self to get datacenter: err="Unexpected response code: 403 (ACL not found)"
2021-07-15T18:59:36.069Z [INFO]  Retrying in 1s
2021-07-15T18:59:37.070Z [ERROR] Failure: calling /agent/self to get datacenter: err="Unexpected response code: 403 (ACL not found)"
2021-07-15T18:59:37.070Z [INFO]  Retrying in 1s
2021-07-15T18:59:38.072Z [ERROR] Failure: calling /agent/self to get datacenter: err="Unexpected response code: 403 (ACL not found)"
2021-07-15T18:59:38.072Z [INFO]  Retrying in 1s

```

Since this job never successfully completes the secondary region cannot come online due to missing secrets such as the client token, mesh gateway token etc...
