### ISSUE TITLE
How to use client daemonset

### ISSUE THREAD

**Issue by pondohva** [hashicorp/consul-helm#108]
Hello. I'm a little bit confused about how client daemonset is supposed to be used.
I see only 1 option:

1. create pod and set NODE_IP from downward API
2. connect to NODE_IP:8500

But it won't work after pod live migration. Old node can be removed and we have to destroy this pod.

I believe simple deployment with N replicas of agent and service for client will work better, but I'm not sure about random switching between agents using service.

**Comment by adomenech73** [comment]
I'm facing similar problem, but what I understood is that only is needed the node ip to find consul client.

from: https://www.consul.io/docs/platform/k8s/run.html

```The clients expose the Consul HTTP API via a static port (default 8500) bound to the host port. This enables all other pods on the node to connect to the node-local agent using the host IP that can be retrieved via the Kubernetes downward API```

So as I'm trying to connect a Spring service I just added a new env var to my deployment as:

```yaml
        - name: SPRING_CLOUD_CONSUL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

The problem is that I'm still getting "Connection refused" errors event if consul client on the same node doesn't show any error on the logs and it's supposed to be listening on this specific host service port. 

So I guess I'm still missing something

**Comment by adomenech73** [comment]
In my case, I solved using status.hostIP to get the correct ip on the var as the daemonset publish 8500 on host level also.

**Comment by pondohva** [comment]
> In my case, I solved using status.hostIP to get the correct ip on the var as the daemonset publish 8500 on host level also.

It works when you don't use up/down scaling and/or preemptible nodes.

**Comment by adomenech73** [comment]
What about something like this?:

```yaml
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```
This way you can use $PODIP and $HOSTIP in container level so you pass there the information about allocation, if the container changes the node the vars should be updated.
