### ISSUE TITLE
failed connect-injector deployment on installation of consul helm

### ISSUE THREAD

**Issue by R-Lamberson** [hashicorp/consul-helm#141]
Assistance with how to troubleshooting the install of Connect Injector on Azure Kubernetes environment appreciated 

deployment logs show the following

```
Usage: consul-k8s [--version] [--help] <command> [<args>] 

Available commands are: 
    sync-catalog    Sync Kubernetes services and Consul services. 
    version         Prints the version
```

below is the values.yaml for the consul helm installation
```
global:
  enabled: true
  image: "consul:latest"
  imageK8S: "hashicorp/consul-k8s:0.7.0"
  domain: consul
  datacenter: dc1

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  connect: true
  storage: 10Gi
  storageClass: storageclass.beta.kubernetes.io
#  resources: |
#    requests:
#      memory: "10Gi"
#    limits:
#      memory: "10Gi"
  disruptionBudget: 
    enabled: false
    maxUnavailable: 1 
  extraConfig: |
    { 
      "log_level": "DEBUG" 
    }    
  extraVolumes: []

client:
  enabled: true
  grpc: true
#  resources: |
#    requests:
#      memory: "10Gi"
#    limits:
#      memory: "10Gi"
  extraConfig: |
    {}
  extraVolumes: []

dns:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer

syncCatalog:
  # True if you want to enable the catalog sync. "-" for default.
  enabled: false
  image: "hashicorp/consul-k8s:0.7.0"
  default: true # true will sync by default, otherwise requires annotation

  # toConsul and toK8S control whether syncing is enabled to Consul or K8S
  # as a destination. If both of these are disabled, the sync will do nothing.
  toConsul: true
  toK8S: true

  # k8sPrefix is the service prefix to prepend to services before registering
  # with Kubernetes. For example "consul-" will register all services
  # prepended with "consul-". (Consul -> Kubernetes sync)
  k8sPrefix: "consul-"

  # k8sTag is an optional tag that is applied to all of the Kubernetes services
  # that are synced into Consul. If nothing is set, defaults to "k8s".
  # (Kubernetes -> Consul sync)
  k8sTag: null

  # syncClusterIPServices syncs services of the ClusterIP type, which may
  # or may not be broadly accessible depending on your Kubernetes cluster.
  # Set this to false to skip syncing ClusterIP services.
  syncClusterIPServices: true

  # nodePortSyncType configures the type of syncing that happens for NodePort
  # services. The valid options are: ExternalOnly, InternalOnly, ExternalFirst.
  # - ExternalOnly will only use a node's ExternalIP address for the sync
  # - InternalOnly use's the node's InternalIP address
  # - ExternalFirst will preferentially use the node's ExternalIP address, but
  #   if it doesn't exist, it will use the node's InternalIP address instead.
  nodePortSyncType: ExternalFirst

  # aclSyncToken refers to a Kubernetes secret that you have created that contains
  # an ACL token for your Consul cluster which allows the sync process the correct
  # permissions. This is only needed if ACLs are enabled on the Consul cluster.
  aclSyncToken:
    secretName: null
    secretKey: null

connectInject:
  enabled: true # "-" disable this by default for now until the image is public
  image: "hashicorp/consul-k8s:0.7.0" # image for consul-k8s that contains the injector
  default: true
  # imageConsul: "consul:latest"
  # imageEnvoy: "envoy/envoy-alpine"
  namespaceSelector: null
  certs:
    secreteName: null
  #  certName: tls.crt
  #  keyName: tls.key
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  # Example:
  # nodeSelector: |
  #   beta.kubernetes.io/arch: amd64
  # nodeSelector: null
```
