### ISSUE TITLE
connect latency

### ISSUE THREAD

**Issue by bakhtyarkf** [hashicorp/consul-helm#153]
if I enable consul connect, I have huge latency when I send a request to the services that are in my kubernetes cluster, but as soon as I disable the connect sidecar injection and redeploy again the latency goes away.

here is my values.yml
```
# Available parameters and their default values for the Consul chart.

global:

  enabled: true

  domain: consul

  image: "consul:1.4.4"
  imageK8S: "hashicorp/consul-k8s:0.7.0"

  datacenter: dc1

  enablePodSecurityPolicies: false

  gossipEncryption:
    enabled: false
    secretName: consul
    secretKey: gossip-encryption-key

server:
  enabled: "-"
  image: null
  replicas: 3
  bootstrapExpect: 3 # Should <= replicas count

  enterpriseLicense:
    secretName: null
    secretKey: null

  storage: 10Gi
  storageClass: null
  connect: true
  resources: null

  updatePartition: 0

  disruptionBudget:
    enabled: true

    maxUnavailable: null

  extraConfig: |
    {}

  extraVolumes: []

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname

  tolerations: ""

  nodeSelector: null

  priorityClassName: ""

  annotations: null


  extraEnvironmentVars: {}
client:
  enabled: true
  image: null
  join: null

  grpc: true


  resources: null

  extraConfig: |
    {}

  extraVolumes: []

  tolerations: ""

  nodeSelector: null
  priorityClassName: ""


  annotations: null

  extraEnvironmentVars: {}

dns:
  enabled: "-"

ui:

  enabled: "-"

  service:
    enabled: true
    type: null
    annotations: null
    additionalSpec: null


syncCatalog:

  enabled: true
  image: null
  default: true # true will sync by default, otherwise requires annotation

  toConsul: true
  toK8S: true

  k8sPrefix: null

  k8sTag: null

  syncClusterIPServices: true

  nodePortSyncType: ExternalFirst

 
  aclSyncToken:
    secretName: null
    secretKey: null

 
  nodeSelector: null

connectInject:
  enabled: true
  image: null 
  default: true 


  imageConsul: null
  imageEnvoy: null

  namespaceSelector: null


  certs:

    secretName: null

    caBundle: ""

    certName: tls.crt
    keyName: tls.key
  nodeSelector: null
```
