### ISSUE TITLE
Ability to specify Consul client daemonset affinity

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/consul-helm#164]
Consul server affinity was added via https://github.com/hashicorp/consul-helm/pull/18, client and server node selectors via https://github.com/hashicorp/consul-helm/pull/135 and client and server tolerations via https://github.com/hashicorp/consul-helm/pull/117 but I would like to be able to specify affinity for the Consul client, e.g.

```yaml
# Don't run on master nodes.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: DoesNotExist
```
