### ISSUE TITLE
bootstrapACLs getting stuck on install

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/consul-helm#182]
Running a fresh installation using bootstrapACLs is running into a deadlock

The consul-server-acl-init job is responsible for bootstrapping ACLs on the server (generating the bootstrap token & generating the server token) and is a job with a post-install hook.
The consul client pod has an initContainer "client-acl-init" which is stuck waiting for that bootstrap token secret and so, pod installation won't finish until the bootstrap token exists.

So, the consul-server-acl-init job will only kick off when installation is finished but installation can't finish until the consul-server-acl-init job runs.

**Comment by adilyse** [comment]
The new process definitely introduces a delay to having the cluster set up correctly, but it should eventually complete. If you wait a couple minutes, does the cluster become available?

Because the cluster must be up and have a leader elected before any ACL bootstrapping can happen, there's unfortunately no way to completely remove the delay.

**Comment by infa-bsurber** [comment]
the servers come up fine, it's the client pod that blocks (testing w/ minikube):
```
kubectl --namespace local-ha-vault get pods
NAME                           READY   STATUS     RESTARTS   AGE
vault-consul-consul-jfhwv      0/1     Init:0/1   0          17m
vault-consul-consul-server-0   1/1     Running    0          17m
vault-consul-consul-server-1   1/1     Running    0          17m
vault-consul-consul-server-2   1/1     Running    0          17m
```

**Comment by adilyse** [comment]
I admit I haven't tried it out on minikube. Can you list the secrets that exist in your environment? And are you able to see the logs from the server init job? There might be more info available there.

**Comment by infa-bsurber** [comment]
the server init job isn't kicking off as it's a "post-install" hook
i'm currently rerunning so I can get the secrets list in a sec

**Comment by infa-bsurber** [comment]
```
k --namespace local-ha-vault get secrets
NAME                                              TYPE                                  DATA   AGE
consul-tls                                        Opaque                                4      25s
default-token-t6bdz                               kubernetes.io/service-account-token   3      4d1h
dlcloudtrustops                                   kubernetes.io/dockerconfigjson        1      4d1h
gossip-encryption-vault-consul                    Opaque                                2      24s
vault-consul-consul-client-token-vrk4g            kubernetes.io/service-account-token   3      24s
vault-consul-consul-server-acl-init-token-wzv7v   kubernetes.io/service-account-token   3      24s
vault-consul-consul-server-token-fmsbp            kubernetes.io/service-account-token   3      24s
```

**Comment by infa-bsurber** [comment]
so yeah, no `vault-consul-consul-client-acl-token` secret showing up there because the bootstrap job isn't kicking off

```
kubectl --namespace local-ha-vault get jobs
No resources found.
```

**Comment by adilyse** [comment]
Hmm, that's not right. Which version of Helm are you using? We just had some issues filed with Helm 2.14. It'd be good to rule that out.

**Comment by infa-bsurber** [comment]
v2.13.1 server & client

**Comment by infa-bsurber** [comment]
here's what helm template shows me for the server-acl-init job:
```
apiVersion: batch/v1                                                                                                                                                               [146/1989]
kind: Job                    
metadata:                                                                                      
  name: vault-consul-consul-server-acl-init                                             
  namespace: local-ha-vault                                                  
  labels:                                                    
    app: consul                                                                  
    chart: consul-helm                                                                                      
    heritage: Tiller                       
    release: vault-consul                                                           
  annotations:                                                                          
    "helm.sh/hook": post-install                                               
    "helm.sh/hook-weight": "0"                      
    "helm.sh/hook-delete-policy": hook-succeeded                  
spec:                                                                           
  template:                                                                           
    metadata:                                                                                         
      name: vault-consul-consul-server-acl-init                                      
      labels:                                                                        
        app: consul                                                           
        chart: consul-helm                                                                         
        release: vault-consul                                                               
        component: server-acl-init                                                     
      annotations:                                                                   
        "consul.hashicorp.com/connect-inject": "false"                                         
    spec:                                                                               
      restartPolicy: Never                                                   
      serviceAccountName: vault-consul-consul-server-acl-init                     
      containers:                                                                
        - name: post-install-job                                                                            
          image: hashicorp/consul-k8s:0.8.1
          env:                                                                      
            - name: NAMESPACE                                                           
              valueFrom:                                                                                                                                                                    
                fieldRef:                                                                                                                                                                   
                  fieldPath: metadata.namespace
          command:        
            - "/bin/sh"
            - "-ec"
            - |
              consul-k8s server-acl-init \
                -release-name=vault-consul \
                -k8s-namespace=local-ha-vault \
                -acl-binding-rule-selector=serviceaccount.name!=default \
                -expected-replicas=3
```
