### ISSUE TITLE
consul-sync-catalog pod crashes when only syncing to consul catalog

### ISSUE THREAD

**Issue by tomwganem** [hashicorp/consul-helm#21]
I'm trying to integrate consul in our kubernetes cluster and have it connect to an existing consul cluster. That part works fine. What's not working is enabling "syncCatalog". For now, I just want kubernetes services in the consul catalog. So I've disabled sync to kubernetes. But the consul-sync-catalog pod immediately crashes. The error message is not entirely helpful.

```shell
$ kubectl -n consul logs -f consul-sync-catalog-d888cf85d-dpvjz
2018-10-05T06:25:18.706Z [INFO ] to-consul/source: starting runner for endpoints
2018-10-05T06:25:18.707Z [INFO ] to-consul/sink: ConsulSyncer quitting
ERROR: logging before flag.Parse: E1005 06:25:18.707409       7 controller.go:115] Error syncing cache
ERROR: logging before flag.Parse: E1005 06:25:18.707434       7 controller.go:115] Error syncing cache
```

Here's my values.yaml file.
```yaml
---
global:
  enabled: true
  domain: consul
  image: consul:1.2.3
  imageK8S: hashicorp/consul-k8s:0.1.0
  datacenter: aoc-devtest
server:
  enabled: "-"
  image:
  replicas: 3
  bootstrapExpect: 3
  storage: 10Gi
  storageClass: ibmc-file-bronze
  connect: true
  resources: {}
  updatePartition: 0
  disruptionBudget:
    enabled: true
    maxUnavailable:
  extraConfig: |
    {
      "encrypt": "secretkey",
      "retry_join_wan": [
        "10.115.173.171",
        "10.115.173.188",
        "10.115.173.176"
      ]
    }
  extraVolumes: []
client:
  enabled: "-"
  image:
  join:
  resources: {}
  extraConfig: |
    {
      "encrypt": "secretkey"
    }
  extraVolumes: []
dns:
  enabled: "-"
ui:
  enabled: "-"
  service:
    enabled: true
    type:
syncCatalog:
  enabled: "-"
  image:
  toConsul: true
  toK8S: false
  k8sPrefix:
connectInject:
  enabled: false
  image: TODO
  default: false
  caBundle: ''
  namespaceSelector:
  certs:
    secretName:
    caBundle: ''
    certName: tls.crt
    keyName: tls.key
```
