### ISSUE TITLE
connectInject enabled | caBundle can not be empty

### ISSUE THREAD

**Issue by ljmsc** [hashicorp/consul-helm#213]
when I want to use connectInject I have to set the caBundle parameter even if the secretName is null but the documentation says otherwise.

```
connectInject:
  enabled: true
  default: false
  certs:
    # secretName is the name of the secret that has the TLS certificate and
    # private key to serve the injector webhook. If this is null, then the
    # injector will default to its automatic management mode that will assign
    # a service account to the injector to generate its own certificates.
    secretName: null

    # caBundle is a base64-encoded PEM-encoded certificate bundle for the
    # CA that signed the TLS certificate that the webhook serves. This must
    # be set if secretName is non-null.
    caBundle: ""
```

The error response is the following:
```
Error: error validating "": error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[0].clientConfig): missing required field "caBundle" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig
```
