### ISSUE TITLE
Consul server K8s, error connect external consul client server

### ISSUE THREAD

**Issue by yohandion** [hashicorp/consul-helm#220]
Hello,

I have deployed on k8s a consul cluster server.
I am trying to connect my consul client (external k8s server) on this cluster, but I have a timeout.

```sh
==> Joining cluster...
    2019/08/16 18:29:42 [INFO] agent: (LAN) joining: [ {{ .Values.consul.url }} ]
    2019/08/16 18:29:52 [WARN] agent: (LAN) couldn't join: 0 Err: 1 error occurred:
        * Failed to join XXX.XXX.XXX.XXX: dial tcp XXX.XXX.XXX.XXX:8301: i/o timeout

==> 1 error occurred:
        * Failed to join XXX.XXX.XXX.XXX: dial tcp XXX.XXX.XXX.XXX:8301: i/o timeout
```

On k8s my service expose all the necessary ports (I thinks :))

```yaml
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
```

I thinks the issue come from my ingress, but I don't know how fixe it.
The agent tries to connect on consul server on port 8301, but the ingress don't expose it.

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.consul.ingress }}
spec:
  rules:
    - host: {{ .Values.consul.url }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.consul.service }}
              servicePort: 8500
```

Any help will be welcome.

Thanks
