### ISSUE TITLE
Consul-helm  0.8.1 sync catalog fail 

### ISSUE THREAD

**Issue by luweiv9988** [hashicorp/consul-helm#222]
* Version:
```
kubectl: v1.12.6-aliyun.1

helm: v2.11.0

consul-helm: v0.8.1
```

* pod status:
```
$ kubelet get po 

juhe-consul-dq7gl                           1/1     Running            0          161m
juhe-consul-jnf6x                           1/1     Running            0          161m
juhe-consul-pzwbk                           1/1     Running            0          161m
juhe-consul-server-0                        1/1     Running            0          161m
juhe-consul-server-1                        1/1     Running            0          161m
juhe-consul-server-2                        1/1     Running            0          161m
juhe-consul-sync-catalog-8647c76dbf-qpmth   0/1     CrashLoopBackOff   53         161m
```

* pod logs:
```
$ kubectl logs juhe-consul-sync-catalog-8647c76dbf-qpmth

...
[GET /health/ready] Error getting leader status: Get http://DOCKER_HOST_IP:8500/v1/status/leader: dial tcp DOCKER_HOST_IP:8500: connect: connection refused
...
```

* values.yaml
```
global:
  enabled: true
  domain: consul
  image: "consul:1.5.0"
  imageK8S: "hashicorp/consul-k8s:0.9.0"
  datacenter: dc1
  enablePodSecurityPolicies: false
  gossipEncryption:
    secretName: null
    secretKey: null
  bootstrapACLs: false
server:
  enabled: "-"
  image: null
  replicas: 3
  bootstrapExpect: 3 # Should <= replicas count
  enterpriseLicense:
    secretName: null
    secretKey: null
  storage: 10Gi
  storageClass: "alicloud-nas"
  connect: true
  resources: null
  updatePartition: 0
  disruptionBudget:
    enabled: true
    maxUnavailable: null
  extraConfig: |
    {}
  extraVolumes: []
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
  tolerations: ""
  nodeSelector: null
  priorityClassName: ""
  annotations: null
  extraEnvironmentVars: {}
client:
  enabled: "-"
  image: null
  join: null
  grpc: false
  resources: null
  extraConfig: |
    {}
  extraVolumes: []
  tolerations: ""
  nodeSelector: null
  priorityClassName: ""
  annotations: null
  extraEnvironmentVars: {}
  snapshotAgent:
    enabled: false
    replicas: 2
    configSecret:
      secretName: null
      secretKey: null
dns:
  enabled: "-"

ui:
  enabled: "-"
  service:
    enabled: true
    type: LoadBalancer
    annotations: null
    additionalSpec: null
syncCatalog:
  enabled: true
  image: null
  default: true # true will sync by default, otherwise requires annotation
  toConsul: true
  toK8S: true
  k8sPrefix: null
  consulPrefix: null
  k8sTag: null
  syncClusterIPServices: true
  nodePortSyncType: ExternalFirst
  aclSyncToken:
    secretName: null
    secretKey: null
  nodeSelector: null
connectInject:
  enabled: false
  image: null # image for consul-k8s that contains the injector
  default: false # true will inject by default, otherwise requires annotation
  imageConsul: null
  imageEnvoy: null
  namespaceSelector: null
  certs:
    secretName: null
    caBundle: ""
    certName: tls.crt
    keyName: tls.key
  nodeSelector: null
  aclBindingRuleSelector: "serviceaccount.name!=default"
  centralConfig:
    enabled: false
    defaultProtocol: null
    proxyDefaults: |
      {}
meshGateway:
  enabled: false
  globalMode: local
  replicas: 2
  wanAddress:
    port: 443
    useNodeIP: true
    useNodeName: false
    host: ""
  service:
    enabled: false
    type: ClusterIP
    port: 443
    nodePort: null
    annotations: null
    additionalSpec: null
  imageEnvoy: envoyproxy/envoy:v1.10.0
  hostNetwork: false
  dnsPolicy: null
  consulServiceName: ""
  containerPort: 443
  hostPort: null
  enableHealthChecks: true
  resources: |
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: mesh-gateway
          topologyKey: kubernetes.io/hostname
  tolerations: null
  nodeSelector: null
  priorityClassName: ""
  annotations: null
```
