### ISSUE TITLE
Pods goes in pending state due to podAntiAffinity rules 

### ISSUE THREAD

**Issue by msidd111** [hashicorp/consul-helm#243]
I have three nodes cluster on aws eks when I restart nodes pods will stay in pending state due to podAntiAffinity rules.

**Comment by msidd111** [comment]
Kubectl get pods will show the pending state. 


kubectl describe pod <server pod> will show the following

Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  37m (x2 over 37m)   default-scheduler  0/2 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 1 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  36m (x6 over 36m)   default-scheduler  0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 1 node(s) had taints that the pod didn't tolerate, 1 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  95s (x44 over 36m)  default-scheduler  0/3 nodes are avai

**Comment by lkysow** [comment]
Thanks. So to reproduce I create an EKS cluster, run `helm install`, then restart the nodes from the AWS Console?

Have you overridden any of the values.yaml settings with your ow?

**Comment by tongpu** [comment]
I have the feeling that the node might have been tainted because of issues with disconnecting an EBS volume from the node.

**Comment by lkysow** [comment]
Hey Lukas, I'm not super familiar with EKS. How might that occur?

**Comment by tongpu** [comment]
It's not specific to EKS but a generic Kubernetes issue (see kubernetes/kubernetes#53059 for other examples). I remember that if the attachment/detachment takes too long the volume attachment controller taints the node so that no further pods can be scheduled on that node and that could be the case here.

**Comment by msidd111** [comment]
The issue with affinity rules. It works after I removed affinity rules.

**Comment by lkysow** [comment]
@msidd111 thanks for the response. How did the Pods get scheduled there in the first place?
If you have 3 nodes and are using the default affinity rules:
```
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
```

Then there should be no problem scheduling the 3 pods to the 3 nodes.
