### ISSUE TITLE
Cannot use `envoy_tracing_json`within `proxyDefaults`

### ISSUE THREAD

**Issue by sylvainOL** [hashicorp/consul-helm#269]
#### Overview of the Issue

I'm not able to use `envoy_tracing_json` or `envoy_tracing_json` within `proxyDefaults`.

#### Reproduction Steps

1. use consul-helm with the following values:
   ```yaml
   ---
   global:
     enabled: true
   
   server:
     replicas: 1
     bootstrapExpect: 1
     connect: true
     storageClass: nfs-client
   
   client:
     grpc: true
   
   ui:
     enabled: true
   
   syncCatalog:
     enabled: true
   
   connectInject:
     enabled: true
     default: true
     centralConfig:
       enabled: true
       defaultProtocol: http
       proxyDefaults: |
         {
            "envoy_prometheus_bind_addr": "0.0.0.0:9100",
            "envoy_tracing_json": {
               "http": {
                  "name": "envoy.zipkin",
                  "typed_config": {
                     "@type": "type.googleapis.com/envoy.config.trace.v2.ZipkinConfig",
                     "collector_cluster": "jaeger",
                     "collector_endpoint": "/api/v1/spans",
                     "shared_span_context": false
                  }
               }
            },
            "envoy_extra_static_clusters_json": {
               "name": "jaeger",
               "connect_timeout": "1s",
               "type": "strict_dns",
               "lb_policy": "round_robin",
               "load_assignment": {
                  "cluster_name": "jaeger",
                  "endpoints": [
                     {
                        "lb_endpoints": [
                           {
                              "endpoint": {
                                 "address": {
                                    "socket_address": {
                                       "address": "jaeger.mesh-collector",
                                       "port_value": 9411
                                    }
                                 }
                              }
                           }
                        ]
                     }
                  ]
               }
            }
         }
   ```

1. Create a deployment
1. View error:

```
Config entry "service-defaults" / "jaeger-jaeger-operator" not updated
Registered service: jaeger-jaeger-operator-sidecar-proxy
Registered service: jaeger-jaeger-operator
==> failed parsing Proxy.Config: 2 error(s) decoding:

* 'envoy_extra_static_clusters_json' expected type 'string', got unconvertible type 'map[string]interface {}'
* 'envoy_tracing_json' expected type 'string', got unconvertible type 'map[string]interface {}'
```

I've tried: 

```yaml
proxyDefaults: |
  {
    "envoy_prometheus_bind_addr": "0.0.0.0:9100",
    "envoy_tracing_json": "{"http": {"name": "envoy.zipkin", "typed_config": { "@type": "type.googleapis.com/envoy.config.trace.v2.ZipkinConfig", "collector_cluster": "jaeger", "collector_endpoint": "/api/v1/spans", "shared_span_context": false } } }"",
    "envoy_extra_static_clusters_json": "{ "name": "jaeger", "connect_timeout": "1s", "type": "strict_dns", "lb_policy": "round_robin", "load_assignment": { "cluster_name": "jaeger", "endpoints": [{ "lb_endpoints": [{ "endpoint": { "address": { "socket_address": { "address": "jaeger.mesh-collector", "port_value": 9411 } } } } ] } ] } }"
  }
```

```yaml
proxyDefaults: |
  {
    "envoy_prometheus_bind_addr": "0.0.0.0:9100",
    "envoy_tracing_json": '{"http": {"name": "envoy.zipkin", "typed_config": { "@type": "type.googleapis.com/envoy.config.trace.v2.ZipkinConfig", "collector_cluster": "jaeger", "collector_endpoint": "/api/v1/spans", "shared_span_context": false } } }',
    "envoy_extra_static_clusters_json": '{ "name": "jaeger", "connect_timeout": "1s", "type": "strict_dns", "lb_policy": "round_robin", "load_assignment": { "cluster_name": "jaeger", "endpoints": [{ "lb_endpoints": [{ "endpoint": { "address": { "socket_address": { "address": "jaeger.mesh-collector", "port_value": 9411 } } } } ] } ] } }'
  }
```

```yaml
proxyDefaults: |
  {
    "envoy_prometheus_bind_addr": "0.0.0.0:9100",
    "envoy_tracing_json": "{\"http\": {\"name\": \"envoy.zipkin\", \"typed_config\": { \"@type\": \"type.googleapis.com/envoy.config.trace.v2.ZipkinConfig\", \"collector_cluster\": \"jaeger\", \"collector_endpoint\": \"/api/v1/spans\", \"shared_span_context\": false } } }",
    "envoy_extra_static_clusters_json": "{ \"name\": \"jaeger\", \"connect_timeout\": \"1s\", \"type\": \"strict_dns\", \"lb_policy\": \"round_robin\", \"load_assignment\": { \"cluster_name\": \"jaeger\", \"endpoints\": [{ \"lb_endpoints\": [{ \"endpoint\": { \"address\": { \"socket_address\": { \"address\": \"jaeger.mesh-collector\", \"port_value\": 9411 } } } } ] } ] } }"
  }
```

but none of them worked (some crash consul server pod, some crash the sidecar...)

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```shell
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 62
	services = 62
build:
	prerelease =
	revision = 9be6dfc3
	version = 1.6.1
consul:
	acl = disabled
	known_servers = 1
	server = false
runtime:
	arch = amd64
	cpu_count = 32
	goroutines = 590
	max_procs = 32
	os = linux
	version = go1.12.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 4
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```shell
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 9be6dfc3
	version = 1.6.1
consul:
	acl = disabled
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 10.233.65.27:8300
	server = true
raft:
	applied_index = 10031
	commit_index = 10031
	fsm_pending = 0
	last_contact = 0
	last_log_index = 10031
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:53bfea2a-aa00-2ee2-13c5-c9b682e903f9 Address:10.233.65.27:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 32
	goroutines = 345
	max_procs = 32
	os = linux
	version = go1.12.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

* OS: Debian 9
* Kubernetes: 1.15.3
* Helm: 2.14.3
* Installer: Kubespray
* CNI: cilium
