### ISSUE TITLE
Cant get connectInject.namespaceSelector to work

### ISSUE THREAD

**Issue by Spaceman1861** [hashicorp/consul-helm#276]
#### Overview of the Issue

Hi I'm trying to setup consul to only get connectInject resources within a specific namespace.

According to the values.yaml in the helm chart I think I can set connectInject.namespaceSelector to do this but my command isn't working and I can't figure out whats going wrong.

Its probably me being a derp but it might be a legit bug.

#### Reproduction Steps

```helm delete consul-$namespace --purge;
helm install --name=consul-$namespace ./consul-helm `
    --namespace="$namespace" `
    --set global.datacenter="hashidc1" `
    --set ui.service.type="LoadBalancer" `
    --set connectInject.enabled=true `
    --set connectInject.namespaceSelector="$namespace" `
    --set client.enabled=true `
    --set client.grpc=true `
    --set server.replicas=1 `
    --set server.bootstrapExpect=1 `
    --set server.disruptionBudget.enabled=true `
    --set server.disruptionBudget.maxUnavailable=0;`
```
I get this response

```helm : Error: release consul-dev failed: MutatingWebhookConfiguration in version "v1beta1" cannot be 
handled as a MutatingWebhookConfiguration: v1beta1.MutatingWebhookConfiguration.Webhooks: 
[]v1beta1.Webhook: v1beta1.Webhook.NamespaceSelector: readObjectStart: expect { or n, but found ", error 
found in hashicorp/consul#10 byte of ...|elector":"dev","rule|..., bigger context 
...|jector.consul.hashicorp.com","namespaceSelector":"dev","rules":[{"apiGroups":[""],"apiVersions":["v1|..
```

### Operating system and Environment details

Windows , Docker desktop latest stable consul

**Comment by lkysow** [comment]
Hi Sean,
You can't set `connectInject.namespaceSelector` to just a string. It's actually expecting an object that's set via a YAML string.
See these docs for some valid namespaceSelectors:
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector

For example if you wanted
```yaml
  namespaceSelector:
    matchExpressions:
    - key: runlevel
      operator: NotIn
      values: ["0","1"]
```

Then you'd need to set in your own `values.yaml` file:

```yaml
connectInject:
  namespaceSelector: |
    matchExpressions:
    - key: runlevel
      operator: NotIn
      values: ["0","1"]
```
