### ISSUE TITLE
Pods stuck in crash loop backoff after using gossip encryption

### ISSUE THREAD

**Issue by eahrend** [hashicorp/consul-helm#287]
Hey,

Trying to install consul on a GKE cluster with gossip encryption via helm in a non production environment. 

This is the file I'm currently using during `helm install --name consul --namespace consul -f helm-consul-values.yaml .`

```
global:
  datacenter: consul1
  gossipEncryption:
    secretName: consulsecrets
    secretKey: encrypt



ui:
  service:
    type: 'LoadBalancer'


connectInject:
  enabled: true
syncCatalog:
  enabled: true

client:
  enabled: true
  grpc: true

server:
  replicas: 3
  bootstrapExpect: 3
  disruptionBudget:
    enabled: true
    maxUnavailable: 0     
```

Here is the secret key I'm using, the key was generated via `consul keygen`
```
apiVersion: v1
data:
  encrypt: M6uPsNtl7ScO730oBXl11n7bh0SvcapJZkXpKRQwt6g=
kind: Secret
metadata:
  name: consulsecrets
  namespace: consul    
type: Opaque
```

All the pods are restarting except for the connect-injector-webhook pods, the only line in the logs is:

`==> encrypt has invalid key: illegal base64 data at input byte 1`

This is what I was using to enable gossip encryption on the cluster.
https://github.com/hashicorp/consul-helm/blob/master/values.yaml#L45-L47
