### ISSUE TITLE
ACL bootstrapping returns a 500 error code

### ISSUE THREAD

**Issue by eahrend** [hashicorp/consul-helm#288]
Hey,

Trying to bootstrap the ACL as part of an ongoing POC to secure consul. Following this guide:
https://www.consul.io/docs/platform/k8s/connect.html#accepting-inbound-connections

Cluster information:
```
Master/Node Version: 1.12.10-gke.17
Cloud: GCP/GKE
```

My custom values file:

```
global:
  bootstrapACLs: true  
  datacenter: consul1
  gossipEncryption:
    secretName: null
    secretKey: null

#After the service gets enabled, modify kube-dns stub-domain
dns:
  enabled: true

ui:
  enabled: true
  service:
    type: 'LoadBalancer'


connectInject:
  enabled: true
  default: false
syncCatalog:
  enabled: true

client:
  enabled: true
  grpc: true

server:
  replicas: 3
  bootstrapExpect: 3
  disruptionBudget:
    enabled: true
    maxUnavailable: 0     
```

After I deploy helm, I get the secret, go to the UI and add the bootstrap token. Works just fine, now when I start up the static server listed here:

Manifest file for a static server:

```
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
    # This name will be the service name in Consul.
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
      ports:
        - containerPort: 8080
          name: http
   # If ACLs are enabled, the serviceAccountName must match the Consul service name.
  serviceAccountName: static-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
```

When I create the pod it goes into a crash loop backoff state saying it's failed to init, I see some of the other issues are reporting 403 error codes, however from the consul-connect-inject-init logs:

```
Error logging in: Unexpected response code: 500 (rpc error making call: Unauthorized)
```

I'm not sure if there is any other configuration necessary since the documentation states it should be able to inject the token and log in to consul.
