### ISSUE TITLE
Automatic Secure Pod Communication

### ISSUE THREAD

**Issue by janbotech** [hashicorp/consul-helm#294]
Hello, 

I wasn't able to find much documentation about the subject of how to automate and force tls traffic between pods when using connect sidecar. 

I tried using default specified cert and key from values.yml but in logs it shows that it cannot be found on the server.

Is it possible to automatically create tls certificates and force secure pod communication when consul is installed using helm?

Thanks

**Comment by lkysow** [comment]
Hi,
Are you talking about between pods that have had Envoy injected?
If so, you need to set your `upstreams` to point to services registered in Consul (see https://www.consul.io/docs/platform/k8s/connect.html#connecting-to-connect-enabled-services). 
For example if you set 
```yaml
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "static-server:1234"
```

Then when you talk to `localhost:1234`, the sidecar will encrypt that traffic and send it to the `static-server` service running in another pod.

>I tried using default specified cert and key from values.yml but in logs it shows that it cannot be found on the server.

What cert and key are you talking about here?
