### ISSUE TITLE
failed to sync remote state: No cluster leader

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#323]
_Originally posted by @yueru-mylove in https://github.com/hashicorp/consul-helm/issues/76#issuecomment-570472110_

The consul-0 starting logs is as belows:
>==> Log data will now stream in as it occurs:

    2020/01/03 01:57:14 [INFO]  raft: Initial configuration (index=0): []
    2020/01/03 01:57:14 [INFO] serf: EventMemberJoin: consul-0.dc1 10.244.0.102
    2020/01/03 01:57:14 [INFO]  raft: Node at 10.244.0.102:8300 [Follower] entering Follower state (Leader: "")
    2020/01/03 01:57:14 [INFO] serf: EventMemberJoin: consul-0 10.244.0.102
    2020/01/03 01:57:14 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
    2020/01/03 01:57:14 [INFO] serf: Attempting re-join to previously known node: consul-2: 10.244.0.101:8301
    2020/01/03 01:57:14 [INFO] serf: Attempting re-join to previously known node: consul-2.dc1: 10.244.0.101:8302
    2020/01/03 01:57:14 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)
    2020/01/03 01:57:14 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
    2020/01/03 01:57:14 [INFO] consul: Adding LAN server consul-0 (Addr: tcp/10.244.0.102:8300) (DC: dc1)
    2020/01/03 01:57:14 [INFO] consul: Handled member-join event for server "consul-0.dc1" in area "wan"
    2020/01/03 01:57:14 [INFO] agent: Retry join LAN is supported for: aliyun aws azure digitalocean gce k8s mdns os packet scaleway softlayer triton vsphere
    2020/01/03 01:57:14 [INFO] agent: Joining LAN cluster...
    2020/01/03 01:57:14 [INFO] agent: (LAN) joining: [consul-0.consul.default.svc.cluster.local consul-1.consul.default.svc.cluster.local consul-2.consul.default.svc.cluster.local]
    2020/01/03 01:57:14 [INFO] agent: started state syncer
==> Consul agent running!
    2020/01/03 01:57:14 [WARN] memberlist: Failed to resolve consul-1.consul.default.svc.cluster.local: lookup consul-1.consul.default.svc.cluster.local on 10.10.0.10:53: no such host
    2020/01/03 01:57:14 [WARN] memberlist: Failed to resolve consul-2.consul.default.svc.cluster.local: lookup consul-2.consul.default.svc.cluster.local on 10.10.0.10:53: no such host
    2020/01/03 01:57:14 [INFO] agent: (LAN) joined: 1
    2020/01/03 01:57:14 [INFO] agent: Join LAN completed. Synced with 1 initial agents
    2020/01/03 01:57:17 [WARN] serf: Failed to re-join any previously known node
    2020/01/03 01:57:17 [WARN] serf: Failed to re-join any previously known node
    2020/01/03 01:57:21 [ERR] agent: failed to sync remote state: No cluster leader
    2020/01/03 01:57:22 [WARN]  raft: no known peers, aborting election
    2020/01/03 01:57:42 [ERR] agent: Coordinate update error: No cluster leader
    2020/01/03 01:57:54 [ERR] agent: failed to sync remote state: No cluster leader

And consul-1 and consul-2 only has log:
>==> Log data will now stream in as it occurs:

So I really don't  know why I got this. Consul service: 
```yaml
apiVersion: v1
kind: Service
metadata:
   name: consul
   labels:
     name: consul
spec:
   type: ClusterIP
   clusterIP: None
   ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
   selector:
    app: consul
```

sts file: 
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: consul
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: consul
          image: consul:latest
          args:
            - "agent"
            - "-server"
            - "-bootstrap-expect=3"
            - "-ui"
            - "-data-dir=/consul/data"
            - "-bind=0.0.0.0"
            - "-client=0.0.0.0"
            - "-advertise=$(PODIP)"
            - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
            - "-domain=cluster.local"
            - "-disable-host-node-id"
          volumeMounts:
            - name: data
              mountPath: /consul/data
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
      volumes:
        - name: data
          hostPath:
            path: /home/data
```

Thank you so much.
