### ISSUE TITLE
Document how to run on Kind

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#324]
Kind: https://kind.sigs.k8s.io

The only problem is the servers requiring 3 nodes due to their anti-affinity config. Can either run with
```yaml
server:
  replicas: 1
  bootstrapExpect: 1
```

or
```yaml
server:
  affinity: ""
```

Request from https://github.com/hashicorp/consul-helm/issues/322
