### ISSUE TITLE
Unable to load consul UI

### ISSUE THREAD

**Issue by srimandarbha** [hashicorp/consul-helm#353]
Hello

We are using consul-helm with 3 replicas, we are able to see the catalog nodes but we are unable to access UI on svc. It is giving 500 error with a below message

Below is the custom values
```
root@node1:~# cat consulfull.yml
global:
  enabled: true
  image: "consul:1.6.2"
  datacenter: bn
  imageK8S: "hashicorp/consul-k8s:0.11.0"
  gossipEncryption:
   secretName: consul-gossip-encryption-key
   secretKey: key

server:
  enabled: true
  image: "consul:1.6.2"
  replicas: 3
  bootstrapExpect: 3
  storage: 10Gi
  storageClass: local-storage

client:
  enabled: true
  image: "consul:1.6.2"
  grpc: true
  extraVolumes:
  -  type: "secret"
     name: consul-gossip-encryption-key
     load: true

dns:
  enabled: true

ui:
  enabled: true
  service:
   type: "NodePort"

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: true

connectInject:
  enabled: true
root@node1:~#
```

Error message:
=========

Consul returned an error. You may have visited a URL that is loading an unknown resource. So you can try going back to the root or try re-submitting your ACL token/SecretID by going back to ACL's.

**Comment by srimandarbha** [comment]
Consul returned an error. You may have visited a URL that is loading an unknown resource. So you can try going back to the root or try re-submitting your ACL token/SecretID by going back to ACL's.

**Comment by johncowen** [comment]
HI @srimandarbha ,

Thanks for reporting this, is there any chance you can look in the Network Panel of the Web Inspector in your browser and see which request is giving you the 500 error?

Let me know if you are unsure how to do this and I can help you find it.

Thanks,

**Comment by jiangyongbing24** [comment]
Try to enable bootstrapACLs option

**Comment by lkysow** [comment]
Hi @srimandarbha in addition to finding the request that's giving you the 500 error, can you show us the URL that you're using? Do you get the same error if you `kubectl port-forward` to one of the `consul-server` pods on port 8500?

Also, if you're setting 
```
global:
  gossipEncryption:
   secretName: consul-gossip-encryption-key
   secretKey: key
```
You don't need:
```
  extraVolumes:
  -  type: "secret"
     name: consul-gossip-encryption-key
     load: true
```
