### ISSUE TITLE
Permission denied when registration service entered consul

### ISSUE THREAD

**Issue by jiangyongbing24** [hashicorp/consul-helm#360]
I use the token in the acl-tokens.json file in the mount directory for permission verification.When using this token in spring cloud consul, I found that the permission was denied.Another confusion is why after entering the token in the consul ui, there will only be a message reminding the token to be correct or wrong, and it will not jump to the policy management page. After I tried to install consul by traditional means, I found that after entering the token in the acl of the consul ui, it would jump to the policy management page.

This is my configuration file for consul-helm

```yaml
global:
  image: consul:1.7.0
  imageK8S: hashicorp/consul-k8s:0.11.0
  bootstrapACLs: true
  datacenter: minidc
server:
  replicas: 1
  bootstrapExpect: 1
  storageClass: consul-data
dns:
  enabled: false
ui:
  service:
    type: NodePort
```

Why does this happen? Is my configuration file incorrect or is it the wrong token?
