### ISSUE TITLE
Template error following documentation

### ISSUE THREAD

**Issue by cwebbtw** [hashicorp/consul-helm#363]
Following documentation:

https://www.consul.io/docs/platform/k8s/servers-outside-kubernetes.html

The error is produced:

Error: template: consul/templates/tests/test-runner.yaml:1:14: executing "consul/templates/tests/test-runner.yaml" at <.Values.tests.enabled>: nil pointer evaluating interface {}.enabled

Is the documentation out of date?

**Comment by cwebbtw** [comment]
I understand that I may need to go and add:

```
tests:
  enabled: false
```

and then look at the other errors that happen, but it seems as if either the documentation is out, or I'm doing something wrong.

**Comment by lkysow** [comment]
Hi Christopher,
This error occurs when the `values.yaml` file inside the chart directory doesn't have the keys:
```
tests:
  enabled: false
```

I'm guessing that you've been editing the values.yaml file directly inside the chart? When the chart was updated to use the new `tests.enabled` key, the `values.yaml` included with the chart was also updated. If you had a `config.yaml` file outside of the chart that you were using the override the values (`helm install consul ./consul-helm -f config.yaml`), then you wouldn't be seeing this error. But if you updated the chart and removed the `values.yaml` that came with the updates then you'd run into this error.

**Comment by cwebbtw** [comment]
I started with an empty values.yaml and copied the yaml in the documentation:

https://www.consul.io/docs/platform/k8s/servers-outside-kubernetes.html

> The below config.yaml file shows how to configure the Helm chart to install Consul clients that will join an existing cluster.

```
# config.yaml
global:
  enabled: false

client:
  enabled: true
  # Set this to true to expose the Consul clients using the Kubernetes node
  # IPs. If false, the pod IPs must be routable from the external servers.
  exposeGossipPorts: true
  join:
    - "provider=my-cloud config=val ..."
```

The documentation doesn't quite make this clear.

This is not a request for help, but rather feedback around the documentation on the website.
