### ISSUE TITLE
advertise_addr use envrionment variable failed

### ISSUE THREAD

**Issue by like-inspur** [hashicorp/consul-helm#364]
use server-statfulset to install consul server, and config advertise with POD_IP which is an environment variable defined in statefulset like this:
````
      containers:
      - name: consul
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - agent
        - -bind=0.0.0.0
        - -advertise="${POD_IP}"
````
But pod start failed and output error like this:
log is DEPRECATED and will be removed in a future version. Use logs instead.
````
==> 2 errors occurred:
	* advertise_addr: invalid ip address: "${POD_IP}"
	* advertise_addr: invalid ip address: "${POD_IP}"
````
