### ISSUE TITLE
Consul-Kubernetes Auth Method

### ISSUE THREAD

**Issue by antonyaugustus** [hashicorp/consul-helm#400]
Any one able to give me some suggestions.

I'm trying to use my external consul server agent for my services running inside kubernetes. Here are my helm chart values.
```
global:
 enabled: false
 datacenter: testdc
 gossipEncryption:
 secretName: “consul-gossip-encryption-key”
 secretKey: “key”
client:
 enabled: true
 grpc: true
 exposeGossipPorts: true
 join:
  - “consul01”
  - “consul02”
  - “consul03”
 extraConfig: |
 {
  “log_level”: “DEBUG”
 }
connectInject:
 enabled: true
 default: false
syncCatalog:
 enabled: true
 default: false
 toConsul: true
 toK8S: false
 k8sTag: “k8s-test”
 aclSyncToken:
 secretName: “consul-acl-token-agent”
 secretKey: “key”
```

I have Kubernetes AuthMethod Type with the JWT for Kubernetes Service Account - hashicorp-consul-connect-injector-authmethod-svc-account. This SA is in consul-system namespace and so are the consul agent daemonsets and connect-injector pods. 

I have a test demo pods that are running on “test” namespace.

Policy Definition is pretty open for all service and service_prefix.
```
service “” {
policy = “write”
intentions = “write”
}
service_prefix “” {
policy = “write”
intentions = “write”
}
service_prefix “static-server” {
policy = “write”
}
service_prefix “static-client” {
policy = “write”
}
```

Bound the policy/role to AuthMethod with different selectors. I tried different combination but I assume there are better ways.
```
./consul acl binding-rule create -method=auth-method-consul-test -bind-type=role -bind-name=‘test-ns-role’ -selector=‘serviceaccount.namespace==“test”’
./consul acl binding-rule create -method=auth-method-consul-test -bind-type=role -bind-name=‘test-ns-role’ -selector=‘serviceaccount.namespace==“consul-system”’
./consul acl binding-rule create -method=auth-method-consul-test -bind-type=role -bind-name=‘test-ns-role’ -selector=‘serviceaccount.name==“static-server”’
./consul acl binding-rule create -method=auth-method-consul-test -bind-type=role -bind-name=‘test-ns-role’ -selector=‘serviceaccount.name==“static-client”’
```

Tried to see if I can use the example showed here to connect two services running in k8s.

https://www.consul.io/docs/platform/k8s/connect.html

Below are some of the logs from different containers in static-client pod
```
kubectl logs -n test static-client consul-connect-inject-init
Registered service: static-client-sidecar-proxy
Registered service: static-client
```

Here is the result from trying to access the service from inside the client pod
```
root@static-client:/# curl -v http://127.0.0.1:1234

Rebuilt URL to: http://127.0.0.1:1234/
Hostname was NOT found in DNS cache
Trying 127.0.0.1…
Connected to 127.0.0.1 (127.0.0.1) port 1234 (#0)
GET / HTTP/1.1
User-Agent: curl/7.35.0
Host: 127.0.0.1:1234
Accept: /
Empty reply from server
Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

It looks like the static server is listening

```
kubectl logs -n test static-server static-server
2020/03/26 18:19:51 Server is listening on :8080
```

Thank you again for you assistance.
