### ISSUE TITLE
Client affinity warning

### ISSUE THREAD

**Issue by debjitk** [hashicorp/consul-helm#426]
Here is my client affinity configuration

```
nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: k8s.domain.com/consul
            operator: DoesNotExist
```

While installing the chart i get the following warning,

```
coalesce.go:196: warning: cannot overwrite table with non table for affinity (map[])
```

**Comment by lkysow** [comment]
Hey, you need to set it using a string, e.g.
```yaml
client:
   affinity: |
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: node-role.kubernetes.io/master
             operator: DoesNotExist

```
