### ISSUE TITLE
helm install failing with last version of helm charts

### ISSUE THREAD

**Issue by mlvlup** [hashicorp/consul-helm#432]
Hi guys,

I'm having the following error with the last version 0.19.0 of the charts

`Error: template: consul/templates/tests/test-runner.yaml:1:14: executing "consul/templates/tests/test-runner.yaml" at <.Values.tests.enabled>: nil pointer evaluating interface {}.enabled
`

My values yaml file is as easy as :

```
ui:
 service:
  type: "LoadBalancer"
syncCatalog:
 enabled: true
connectInject:
 enabled: true
client:
 grpc: true
```

It work like charm with my git clone of 2020-04-07 which was 0.18.0
