### ISSUE TITLE
Error No known Consul servers in sidecar proxy when creating new pod 

### ISSUE THREAD

**Issue by rhzs** [hashicorp/consul-helm#440]
Hi, since the last update (v0.20.1) I have experienced error that caused my pod can't be started.

Here is my helm chart `values.yaml`:
```
# config.yaml

# Configure global settings in this section.
global:
  # Specify the Consul image to use
  image: 'consul:1.7.2'
  domain: consul
  datacenter: primarydc
  # Bootstrap ACLs within Consul. This is highly recommended.
  bootstrapACLs: false
  # Gossip encryption
  gossipEncryption:
    secretName: "consul-gossip-key"

# Configure ACLs.
acls:
  manageSystemACLs: false
  createReplicationToken: false
  replicationToken:
    secretName: null
    secretKey: null

# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 3
  storage: 20Gi
  connect: true
  bootstrapExpect: 3
  resources: |
    requests:
      memory: "256Mi"
      cpu: "300m"
    limits:
      memory: "500Mi"
      cpu: "750m"
  # Prevent Consul servers from co-location on Kubernetes nodes.
  affinity: |
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: consul
            release: "0.19.0"
            component: server
        topologyKey: kubernetes.io/hostname
# Configure Consul clients in this section
client:
  resources: |
    requests:
      memory: "128Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "750m"
# Enable and configure the Consul UI.
ui:
  enabled: true
# Configure security for Consul Connect pod injection
connectInject:
  enabled: true
  default: true
  aclBindingRuleSelector: “serviceaccount.name!=default”
```

This is error from the sidecar - consul envoy proxy:
```
Unexpected response code: 500 (could not retrieve initial service_defaults config for service "xxxx-backend-sidecar-proxy": No known Consul servers
```

Any help would be highly appreciated
