### ISSUE TITLE
manageSystemACLs: the ACL token was not written to a Kubernetes secret

### ISSUE THREAD

**Issue by robfras** [hashicorp/consul-helm#445]
Hello,

Using consul-helm v0.20.1, with helm v3.2.0,  for a deployment on google GKE, I have an error when adding the values: 
 ```yaml
acls:
    manageSystemACLs: true
```

The job **hashicorp-consul-server-acl-init** fails with the following logged error: 

`2020-05-04T14:45:47.721Z [ERROR] ACLs already bootstrapped but the ACL token was not written to a Kubernetes secret. We can't proceed because the bootstrap token is lost. You must reset ACLs.`

the consul-server pods have initiated successfully but the **consul-client pods are stuck in Init:0/1 status** and logs says: 
`Error getting Kubernetes secret: secrets "hashicorp-consul-client-acl-token" not found`

when the secret created is named: 
hashicorp-consul-client-token-rrrcd

in my kubernetes namespace. 

Am i missing a configuration ? 

my values are: 
```yaml
global:
  image: "consul:1.7.2"
  domain: consul
  datacenter: dc1
  acls:
    manageSystemACLs: true
  gossipEncryption:
    secretName: "gossip-encryption-key"
    secretKey: "key"
  imageK8S: "hashicorp/consul-k8s:0.14.0"
server:
  replicas: "3"
  bootstrapExpect: "3"
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: {{ template "consul.name" . }}
            release: "{{ .Release.Name }}"
            component: server
        topologyKey: kubernetes.io/hostname
client:
  enabled: true
connectInject:
  enabled: true
  default: true
  aclBindingRuleSelector: “serviceaccount.name!=default”
```
