### ISSUE TITLE
Error while helm install

### ISSUE THREAD

**Issue by Niharika20** [hashicorp/consul-helm#486]
With the latest clone, I am facing the below mentioned error while doing helm install using new values.yaml file.

Error:

```
coalesce.go:195: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:195: warning: destination for resources is a table. Ignoring non-table value requests:
  memory: "128Mi"
  cpu: "250m"
limits:
  memory: "256Mi"
  cpu: "500m"
coalesce.go:195: warning: destination for resources is a table. Ignoring non-table value <nil>
Error: template: consul/templates/server-statefulset.yaml:255:26: executing "consul/templates/server-statefulset.yaml" at <.Values.server.resources>: wrong type for value; expected string; got map[string]interface {}
```

**Comment by lkysow** [comment]
So I can reproduce this if I edit the `values.yaml` to set
```
server:
  resources: null
```

And then I run with a config.yaml
```
server:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"
```

i.e. `helm install consul hashicorp/consul -f config.yaml`

What I don't understand is how your `values.yaml` is different from the one in master.

Can you explain how you're installing and what your config files look like please?
