### ISSUE TITLE
Add metrics support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [hashicorp/consul-helm#494]
```yaml
  serviceMonitor:
    enabled: true
```

**Comment by sergeyshaykhullin** [comment]
@ishustava Does this issue is in someone's roadmap?

I can create PR with `ServiceMonitor`

It will monitor `service/consul-server:8500/v1/agent/metrics?format=prometheus`
I don't get how to use client metrics, does it has separate metrics, or `consul-server` returning all?
P.S. As i understand it is returning all metrics required, so we have to have one root `ServiceMonitor` just for it?

How it might look like
```yaml
server:
  extraConfig: |
    {"telemetry": {"prometheus_retention_time": "120s"}}

  serviceMonitor:
    enabled: true
    interval: ...
    scrapeTimeout: ...
    namespace: ...

client:
  extraConfig: |
    {"telemetry": {"prometheus_retention_time": "120s"}}
```
