### ISSUE TITLE
Ingress Gateway Listeners Configuration

### ISSUE THREAD

**Issue by berkaybayraktar** [hashicorp/consul-helm#518]
Is there any way to provide listeners configuration to ingress gateway via helm chart ? 

For example, I want to use following listener configuration for the ingress gateway. But, I couldn't find a way to set this configuration.

```json
{
  "kind": "ingress-gateway",
  "name": "ingress-gateway",
  "listeners": {
    "port": 8080,
    "protocol": "http",
    "services": [
      {
        "name": "some-service-name"
      }
    ]
  }
}
```

I know that I can set this configuration by using `consul config write` command.

**Comment by blake** [comment]
Hi @berkaybayraktar,

You may use [`ingressGateways.defaults.service.ports`](https://www.consul.io/docs/k8s/helm#v-ingressgateways-defaults-service-ports) to specify the list of ports which should be exposed from the ingress gateway container. Here's an example.

```yaml
ingressGateways:
  enabled: true
  defaults:
    service:
      type: LoadBalancer
      ports:
        - port: 80
        - port: 443
        - port: 8080
```

The ports defined here are not automatically synced to the `ingress-gateway` config entry. You will need to also set the configuration you provided so that Envoy listens on the specified port(s).
