### ISSUE TITLE
[EKS] Cant deploy new pods after enable connectInject

### ISSUE THREAD

**Issue by RomainPhil** [hashicorp/consul-helm#519]
Hi,
for an upgrade of the existent infrastructure i need to deploy a consul cluster on EKS
the actual cni configured is calico.

my repo is 
`NAME            URL                                
hashicorp       https://helm.releases.hashicorp.com`

and my config file came from the doc:

```
connectInject:
  enabled: true
  default: true
  
client:
  enabled: true

ui:
  service:
    type: "LoadBalancer"
```

the deployement for the consul pods works fine

```
ku get pods
NAME                                                          READY   STATUS    RESTARTS   AGE
consul-82r4m                                                  1/1     Running   0          13m
consul-connect-injector-webhook-deployment-8494f8d78b-mv96z   1/1     Running   0          13m
consul-gn44t                                                  1/1     Running   0          13m
consul-pqknb                                                  1/1     Running   0          13m
consul-server-0                                               1/1     Running   0          13m
consul-server-1                                               1/1     Running   0          13m
consul-server-2                                               1/1     Running   0          13m
``` 

when a tried to deploy the following yaml :

```apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
spec:
  containers:
    # This name will be the service name in Consul.
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
      ports:
        - containerPort: 8080
          name: http
    # If ACLs are enabled, the serviceAccountName must match the Consul service name.
  serviceAccountName: static-server```

i ve got the following result: 

```kubectl apply -f deploy_pods/test_inject.yml -n alpha

serviceaccount/static-server created
Error from server (Timeout): error when creating "deploy_pods/inject-consul-test.yml": Timeout: request did not complete within requested timeout```

like the presence of the injector block the creation of new pods.

Thanks
Romain

**Comment by ishustava** [comment]
Hey @RomainPhil 

Thanks for creating this issue! 

This error looks like it's coming from `kubectl`, and the request timeout is referring to `kubectl` trying to talk to the kube API server. Maybe this is just a temporary network hiccup and you could try re-applying again.

**Comment by RomainPhil** [comment]
Hey @ishustava,

thanks for your answer, i've tried with different deployement and it's seem like it only when the injector is deploy than i have this issue.

i tried to deploy some ressource from a deployment for exclude the kubectl part,

```
 ku get deploy 
NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
front-deployment                       0/2     0            0           23s
consul-connect-injector-webhook-deployment   1/1     1            1           105m
```
and when i describe the replicatset 
```
 ku describe replicaset/front-deployment-5966cb4449
Events:
  Type     Reason        Age                   From                   Message
  ----     ------        ----                  ----                   -------
  Warning  FailedCreate  27s (x12 over 5m57s)  replicaset-controller  Error creating: Timeout: request did not complete within requested timeout
```
maybe the consul inject component attach himself to a kubernetes component and block the communication from other api call

**Comment by ishustava** [comment]
Thanks for providing more details. That does look like there is some issue with the injector. 

Could you include the logs from the connect injector and from the consul client from the host where the injector is running?

You've mentioned that you only see this problem when the injector is deployed. Could you try to deploy a pod with injection disabled, for example:

```
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  annotations:
    'consul.hashicorp.com/connect-inject': 'false'
spec:
  containers:
    # This name will be the service name in Consul.
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
      ports:
        - containerPort: 8080
          name: http
    # If ACLs are enabled, the serviceAccountName must match the Consul service name.
  serviceAccountName: static-server
```
