### ISSUE TITLE
Metrics in prometheus format

### ISSUE THREAD

**Issue by sergeyshaykhullin** [hashicorp/consul-helm#537]
When i tried to get metrics in prometheus format `/v1/agent/metrics?format=prometheus` i got `Prometheus is not enabled since its retention time is not positive`.

I found that consul has https://www.consul.io/docs/agent/options.html#telemetry-prometheus_retention_time
How i can set it using helm chart?

**Comment by lkysow** [comment]
Hi, you can set this in the `extraConfig` section of the helm chart for servers and clients:
```yaml
client:
  extraConfig: |
    {"telemetry": {"prometheus_retention_time": "<your value>"}}
server:
  extraConfig: |
    {"telemetry": {"prometheus_retention_time": "<your value>"}}
```
