### ISSUE TITLE
Can I make the service suffix overridable for consul server

### ISSUE THREAD

**Issue by peterklijn** [hashicorp/consul-helm#549]
Hi all,

While upgrading consul from 1.5.1 (using stable/consul) to 1.8.0 (using hashicorp/consul) I noticed the introduction of client and server.
As a result of this, the server has a name suffix `-server` which causes all our microservices that depend on consul's dns name to not being able to reach consul anymore (as the name has changed).

As far as I can tell, you can't override this suffix. Would you be open to a PR where you can override this suffix with any other suffix (including no suffix)?

This is the related template file:
https://github.com/hashicorp/consul-helm/blob/master/templates/server-service.yaml#L10

Thanks in advance,
Peter

**Comment by peterklijn** [comment]
After trying to remove the `-server` suffix by copying the helm charts it seems that the suffix is quite deeply woven into all templates and making it optional would be rather complex.

If worked around it by deploying a second Kubernetes Service that points to the same pods.

**Comment by lkysow** [comment]
Yeah it is pretty endemic. Should we add something to the stable/consul readme about this though? Do you have a sample of the service you needed to add?

**Comment by peterklijn** [comment]
I ended up adding a service which is pretty much a stripped down version of the `server-service` as a separate deployment.
Changed the following:
- Removed the `-server` suffix
- Removed configurability that we don't use
- Not a headless service (removed the `spec.clusterIP`), although that might change

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.consulService.name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
      # This must be set in addition to publishNotReadyAddresses due
      # to an open issue where it may not work:
      # https://github.com/kubernetes/kubernetes/issues/58662
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  # We want the servers to become available even if they're not ready
  # since this DNS is also used for join operations.
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: dns-tcp
      protocol: "TCP"
      port: 8600
      targetPort: dns-tcp
    - name: dns-udp
      protocol: "UDP"
      port: 8600
      targetPort: dns-udp
  selector:
    app: consul
    release:  {{ .Values.consulService.name }}
    component: server

```
