### ISSUE TITLE
How to bootstrap ACL using a well known master token?

### ISSUE THREAD

**Issue by seguidor777** [hashicorp/consul-helm#569]
Hi all,

I am trying to install consul with the managed ACL option and I cannot specify a custom master token.
I have set this option https://www.consul.io/docs/agent/options#acl_tokens_master
However when I install the chart, the ACL init containers fail and show this error
` Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found`

values.yaml
```yaml
global:
  enabled: true
  image: "consul:1.8.1"
  acls:
    manageSystemACLs: true
datacenter: dc1
gossipEncryption:
  secretName: consul
  keyName: gossip_encryption_key
tls:
  enabled: true
  enableAutoEncrypt: true
  caCert: /consul/userconfig/consul/consul.pem
  caKey: /consul/userconfig/consul/consul-key.pem
server:
  replicas: ${consul_replicas}
  bootstrapExpect: ${consul_replicas}
  extraConfig: |
    {
      "connect": {
        "enabled": true,
        "ca_provider": "vault",
        "ca_config": {
          "address": "https://vault:8200",
          "token": "${consul_vault_token}",
          "root_pki_path": "pki-root",
          "intermediate_pki_path": "pki-services",
          "ca_file": "/consul/userconfig/consul/ca.pem"
        }
      },
      "acl": {
        "tokens": {
          "master": "c1039605-4cb2-4316-bede-e0682d333a6f"
        }
      }
    }
  extraVolumes:
    - type: secret
      name: consul
ui:
  enabled: true
```

Extract from the logs
```
consul-consul-mkgcb client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-624xw client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-mkgcb client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-624xw client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-mkgcb client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-624xw client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-mkgcb client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-624xw client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-mkgcb client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-624xw client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-mkgcb client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-624xw client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-mkgcb client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
consul-consul-624xw client-acl-init Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found
```

**Comment by lkysow** [comment]
Hi Jorge,
I'll preface this response with a disclaimer that the chart doesn't really support pre-specifying the master token right now. I think we need to do more work to make this smooth.

There's a couple of things to address here.

1. If you want to set your master token ahead of time, you also need to create a kubernetes secret and pass this to the `global.acls` configuration so that the rest of the ACL bootstrapping can occur. To create the secret, you can run `kubectl create secret generic consul-acl-bootstrap-token --from-literal=token=c1039605-4cb2-4316-bede-e0682d333a6f`.

    Then you can reference this in your helm config:

    ```yaml
    global:
      ....
      acls:
        manageSystemACLs: true
        bootstrapToken:
          secretName: consul-acl-bootstrap-token
          secretKey: token
      ...
    ```

    This will allow the ACL bootstrap job to create the client tokens and other tokens.

1. I see that you're using
    ```yaml
    tls:
      enabled: true
      enableAutoEncrypt: true
      caCert: /consul/userconfig/consul/consul.pem
      caKey: /consul/userconfig/consul/consul-key.pem
    ```

    But `caCert` and `caKey` must reference Kubernetes secrets, e.g.

    ```yaml
    tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-cert
      secretKey: tls.key
    ```

    To create this secrets, you can run something like `kubectl create secret generic consul-ca-cert --from-file=tls.crt=consul-agent-ca.pem --from-file=tls.key=consul-agent-ca-key.pem`

1. Your servers also need a token they can use themselves. Otherwise you'll see errors like `2020-08-12T20:10:39.349Z [WARN]  agent: Coordinate update blocked by ACLs: accessorID=00000000-0000-0000-0000-000000000002`. The ACL bootstrap job usually hands these tokens out to the servers via API, however currently if the bootstrap token is set then we assume the servers already have a token (incorrect in this case). For now I think you'll need to give the servers the bootstrap token in their config file (via acl.tokens.agent) or you'll need to out-of-band make the update token API call to the servers once the cluster is up.

    ```yaml
    server:
    replicas: 1
    bootstrapExpect: 1
    extraConfig: |
      {
        "connect": {
          "enabled": true
        },
        "acl": {
          "tokens": {
            "master": "e7924dd1-dc3f-f644-da54-81a73ba0a178",
            "agent": "e7924dd1-dc3f-f644-da54-81a73ba0a178" <<<<<<<<<<<<<<<< need this
          }
        }
      }
      ```
