### ISSUE TITLE
Cannot upgrade and turn on ACLs

### ISSUE THREAD

**Issue by Throckmortra** [hashicorp/consul-helm#579]
```
post-install-job
2020-08-19T17:43:55.513Z [ERROR] Failure: bootstrapping ACLs - PUT /v1/acl/bootstrap: err="Unexpected response code: 401 (ACL support disabled)"
```

Getting the above error in acl-init pod after applying update to enable ACLs with
`global.acls.manageSystemACLs: true`

**Comment by Throckmortra** [comment]
```
global:
  datacenter: consul
  acls:
    manageSystemACLs: true

ui:
  enabled: true
  type: NodePort
  
syncCatalog:
  enabled: true

server:
  replicas: 3
  bootstrapExpect: 3
  storage: 50Gi
```

my yaml

**Comment by ashwin-venkatesh** [comment]
Hey @Throckmortra 

I used the aforementioned values file and my helm install succeeded. 
Which version of the helm chart are you currently using? Did you see this failure during a helm install or a helm upgrade?

Thanks!

**Comment by ashwin-venkatesh** [comment]
I think I misunderstood the question. My B. Upgrading an installation where the value of  `global.acls.manageSystemACLs` is changed from `false` -> `true` is not currently supported.

**Comment by Throckmortra** [comment]
hello @ashwin-venkatesh that is unfortunate to hear. How would I go about upgrading this without data loss?

**Comment by ashwin-venkatesh** [comment]
yeah. this is definitely an issue. it is EOD here right now, but i'll investigate this tomorrow and see if there is a tentative fix to unblock your situation. ill report back tomorrow with updates

**Comment by Throckmortra** [comment]
@ashwin-venkatesh thank you for looking into this! Are there any other options/configurations we should know about that cannot be enabled after deployment?

**Comment by ashwin-venkatesh** [comment]
Hey @Throckmortra !!

So the error occurs because the server pods do not get restarted with the updated config for ACLs being enabled. I'll work on addressing this so that going forward, changing the value of manageSystemACLs forces the restarting of servers with the updated state.

While that would require a new release, a solution that should unblock you in the interim is introducing an `extraConfig` into the server. Note: This will require the latest consul helm chart.

Here is the values file for the interim fix:

```
global:
  datacenter: consul
  acls:
    manageSystemACLs: true

ui:
  enabled: true
  type: NodePort
  
syncCatalog:
  enabled: true

server:
  replicas: 3
  bootstrapExpect: 3
  storage: 50Gi
  extraConfig: "{}"
```

The addition of the extraConfig should not change the configuration but will force a restart of the server pods which should lead to the ACL init jobs succeeding once the servers start back up.
