### ISSUE TITLE
wrong type for value; expected string; got map[string]interface {}

### ISSUE THREAD

**Issue by metanovii** [hashicorp/consul-helm#602]
helm chart v 0.24.1
helm 3.3.1

values:
```
server:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"
```

```
╰─ helm upgrade --install ./consul -f custom-values-consul.yaml          
                                                                                                                                                            
Release "hashicorp-consul" does not exist. Installing it now.
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value requests:
  memory: "128Mi"
  cpu: "250m"
limits:
  memory: "256Mi"
  cpu: "500m"
Error: template: consul/templates/server-statefulset.yaml:262:26: executing "consul/templates/server-statefulset.yaml" at <.Values.server.resources>: wrong type for value; expected string; got map[string]interface {}
```
