### ISSUE TITLE
How to use deregister_critical_service_after config parameter?

### ISSUE THREAD

**Issue by dontlaugh** [hashicorp/consul-helm#642]
I'm experimenting with using the catalog sync to register a suite of services for environments that are short lived: a few hours at most.

I'd like to keep the transient services from hanging around forever in my catalog. My understanding is that `deregister_critical_service_after` is a configuration one can apply to a service.

Will this work? How do I apply this configuration when using the helm chart?

**Comment by ishustava** [comment]
Hey @dontlaugh, thanks so much for the issue!

Unfortunately, right now there isn't a way to apply this configuration via the sync catalog feature, but it's something that we can add in the future.

**Comment by lkysow** [comment]
The services should be cleaned up by the catalog sync process. If they're not being cleaned up that sounds like a bug. Can you provide us with a way to reproduce?

**Comment by dontlaugh** [comment]
Here is my architecture:

* 3 external Consul servers
* I provide these values to the helm chart

```yaml
global:
  enabled: false
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-token-acl
      secretKey: token
  datacenter: home

server:
  enabled: false

client:
  enabled: true
  join:
    - "consul-01.greymatter.services"
    - "consul-02.greymatter.services"
    - "consul-03.greymatter.services"
  grpc: false
  exposeGossipPorts: true

externalServers:
  enabled: true
  hosts:
    - "consul-01.greymatter.services"
    - "consul-02.greymatter.services"
    - "consul-03.greymatter.services"
  httpsPort: 8500

syncCatalog:
  enabled: true
  # TODO: do not sync services by default. Instead, provide annotations to Service objects
  # https://www.consul.io/docs/k8s/service-sync#sync-enable-disable
  default: true
  toK8S: false
  toConsul: true
  # template this
  k8sTag: "<%= clusterName %>"
  consulPrefix: "<%= clusterName %>-"
  aclSyncToken:
    secretName: consul-token-acl
    secretKey: token
```

I create a cluster with kops, deploy my services + consul, run some tests, and **destroy** the cluster with kops.

My workaround is to disable autosync (which we probably want to do anyway) and explicitly de-sync the service with annotations. 

To reproduce you might try destroying clusters out from under a consul sync catalog deployment.
