### ISSUE TITLE
Consul outage revealed multiple issues with ACLs and snapshot restores with helm-based consul deployment

### ISSUE THREAD

**Issue by Throckmortra** [hashicorp/consul-helm#650]
consul chart version: 0.25
Helm version: 3.0+
K8s version:  1.15.11-eks
 
Hello,

Yesterday we deployed a change to our services that inadvertently spawned around 10k~ consul kv watches. This change DDoS'd our consul cluster and put it into a crash loop. 

Attempts to restore service to the existing cluster by giving it increased resources with the helm chart controls were met with failure.
```
server:
  resources:
    requests:
      memory: "4Gi"
      cpu: "750m"
    limits:
      memory: "4Gi"
      cpu: "750m"
  ....
```
While we significantly increased its allowed resources and could see that these resources were correctly assigned, consul did not respond to the network pressure by increasing its resource consumption. It continued to use minimal resources while the api was beaten down with consul watch queries and the ui and api remained unreachable.

after assessing the logs and using resource limits to attempt to restore service, we noticed the following issues:

When consul-server pods began crashing, restarts immediately ran into ACL issues and node name issues
```
agent.server.fsm: EnsureRegistration failed: error="failed inserting node: Error while renaming Node ID: "REDACTED: Node name REDACTED is reserved by node REDACTED with name REDACTED"
```

```
[ERROR] agent.http: Request error: method=GET url=/v1/agent/self from=REDACTED error="Permission denied"
consul
[ERROR] agent: Coordinate update error: error="ACL not found"
consul
[ERROR] agent.anti_entropy: failed to sync remote state: error="ACL not found"
```

Regardless of what we tried, we were unable to recover this cluster. I believe we only made matters worse as we tried recycling the consul-server pods ourselves without using the `leave_on_terminate` flag

We then decided to restore into a new cluster with consul snapshots. This immediately caused same errors as above. We were unaware that the snapshots also contained previous tokens and node leases. As we had not saved the previous bootstrap token(s) I believe there was no way to do a legitimate restore into a new cluster without reintroducing the issues. We may have been able to mitigate this by reusing the previous tokens. However, this does not explain the node lease problems. 

Our takeaways are thus:
* Consul snapshot restore is incompatible with consul-helm deployments (and maybe incompatible with new clusters?)
* Consul does not respond to network pressure from blocking queries and therefore has no easy means to scale to meet demand (i.e. we can't use increased resource limits to mitigate issues)
* Blocking queries have undocumented limitations

**Comment by Throckmortra** [comment]
This was our initial consul.yml:
```
global:
  datacenter: consul
  acls:
    manageSystemACLs: true
    createReplicationToken: true

ui:
  enabled: true
  service:
    type: NodePort
  
syncCatalog:
  enabled: true

server:
  replicas: 3
  bootstrapExpect: 3
  storage: 50Gi
```


After looking at the errors and issues, we slightly updated the helm chart to the following when attempting to restore service:
```
global:
  datacenter: consul
  acls:
    manageSystemACLs: true
    createReplicationToken: true

ui:
  enabled: true
  service:
    type: NodePort
  
syncCatalog:
  enabled: true

server:
  replicas: 3
  bootstrapExpect: 3
  storage: 50Gi
  resources:
    requests:
      memory: "4Gi"
      cpu: "750m"
    limits:
      memory: "4Gi"
      cpu: "750m"
  extraConfig: |
    {
      "disable_host_node_id": true
    }

client:
  extraConfig: |
    {
      "disable_host_node_id": true
    }
```
