### ISSUE TITLE
connectInject.centralConfig.defaultProtocol doesn't work in federated datacenters

### ISSUE THREAD

**Issue by woz5999** [hashicorp/consul-helm#690]
Setting `connectInject.centralConfig.defaultProtocol` doesn't work in a non-primary datacenter. 

Per https://github.com/hashicorp/consul/pull/6339, Config entries are forwarded to the primary datacenter. However, the connect-inject-init sidecar authentication only generates a locally scoped ACL token. This means that in non-primary datacenters, the inject-init container doesn't have the necessary permissions to create config objects in the primary datacenter.

I'm not sure of the best way to fix this as each individual component is behaving as designed, but the feature is currently broken for services outside the primary datacenter.

**Comment by lkysow** [comment]
Hi Jeff,
With the newly released support of custom resources we'd actually like to move away from supporting `connectInject.centralConfig.defaultProtocol`. Instead, alongside each service's kube yaml, you would include a `ServiceDefaults` custom resource:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: your-service-name
spec:
  protocol: http
```

Would that work better for your use-case?
