### ISSUE TITLE
service-defaults configuration ends up getting 403d due to lack of token permission

### ISSUE THREAD

**Issue by mariusehr1** [hashicorp/consul-helm#735]
### Overview of the Issue

I deploy a service and a deployments, the latter contains the following annotations : 

```
consul.hashicorp.com/connect-service: postgres
consul.hashicorp.com/connect-service-port: "5432"
consul.hashicorp.com/connect-service-protocol: tcp
```
When starting the pod, I get the following logs from the `consul-connect-inject-init`

```
 Error writing config entry service-defaults/postgres: Unexpected response code: 403 (rpc error making call: rpc error making call: rpc error making call: Permission denied)
 Registered service: postgres
 Registered service: postgres-sidecar-proxy
 stream closed
```

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  enable: true
  imageEnvoy: "envoyproxy/envoy-alpine:v1.14.5"
  name: consul
  datacenter: dc3
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key
      secretKey: tls.key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-federation
      secretKey: replicationToken
    replicationToken:
      secretName: consul-federation
      secretKey: replicationToken
  federation:
    enabled: true
  gossipEncryption:
    secretName: consul-federation
    secretKey: gossipEncryptionKey
connectInject:
  enabled: true
  default: true
  healthChecks:
    enabled: false
  envoyExtraArgs: "--log-level debug --disable-hot-restart"
  logLevel: "debug"
meshGateway:
  enabled: true
  replicas: 2
  service:
    enabled: true
    type: LoadBalancer
    port: 9443
controller:
  enabled: true
server:
  replicas: 2
  connect: true
  bootstrapExpect: 2
  extraVolumes:
  - type: secret
    name: vault-config
    load: true
    items:
      - key: config
        path: vault-config.json
  - type: secret
    name: vault-ca
    load: true
    items:
      - key: vault.ca
        path: vault.ca
  extraConfig: |
    {
      "primary_datacenter": "aws",
      "primary_gateways": ["mesh-gateway.domain.com:9443"]
    }
client:
  enabled: true
syncCatalog:
  enabled: true
  image: null
  default: true
  aclSyncToken:
    secretName: consul-federation
    secretKey: replicationToken
  logLevel: trace
```
Here is the policy for my replicationToken : 

```
acl = "write"
operator = "write"
agent_prefix "" {
  policy = "read"
}
node_prefix "" {
  policy = "write"
}
service_prefix "" {
  policy = "read"
  intentions = "read"
}
```
and here is the policy created by the acl manager for my service : 
```
service "postgres" {
	policy = "write"
}
service "postgres-sidecar-proxy" {
	policy = "write"
}
service_prefix "" {
	policy = "read"
}
node_prefix "" {
	policy = "read"
}

```

### Expected behavior

I would expect the acl manager to bootstrap the token with proper permissions in order to register my `service-defaults` configuration.

### Environment details

- `consul-k8s` version: 0.21.0
- `consul-helm` version: 0.27.0
- `values.yaml` used to deploy the helm chart: see above
- Consul version 1.9.0.

Thanks.

Marius

**Comment by lkysow** [comment]
Hi Marius,
Instead of using the `consul.hashicorp.com/connect-service-protocol: tcp` annotation, would you be able to use the new `ServiceDefaults` custom resource instead?

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: postgres
spec:
  protocol: tcp
```

The problem with the annotation is that you can't actually change it afterwards which is unexpected.

I know this doesn't fix the ACL issue, we'd need to look into that, but the custom resource is our recommended way to set the protocol anyway and we're actually looking at deprecating that annotation in the future.
