### ISSUE TITLE
Init containers failing to start.

### ISSUE THREAD

**Issue by shazinahmed** [hashicorp/consul-helm#772]
### Overview of the Issue

On trying to set up a consul cluster with helm install, the init containers for controller and connect-injector-webhook fails to start.

### Reproduction Steps

Steps to reproduce this issue

1. Run `helm install -f consul-config.yaml hashicorp hashicorp/consul` with config below. 
2. The init containers in the controller and connect-injector-webhook fails to start. 

If my understanding is correct, the reason is the created service account secret names which are `hashicorp-consul-controller-token-jxdps` and `hashicorp-consul-connect-injector-webhook-svc-account-tokej6xkc` and the expected secret names which are `hashicorp-consul-controller-acl-token` and `hashicorp-consul-connect-inject-acl-token` respectively don't match. 

Respective manifests:
https://github.com/hashicorp/consul-helm/blob/5321326db4361970791cc9373cb68a283636eab8/templates/connect-inject-deployment.yaml#L67 and

https://github.com/hashicorp/consul-helm/blob/5321326db4361970791cc9373cb68a283636eab8/templates/controller-deployment.yaml#L89

### Logs
```
kubectl logs hashicorp-consul-controller-57b5d47f48-nlcn4 controller-acl-init
Error getting Kubernetes secret: secrets "hashicorp-consul-controller-acl-token" not found
```

and 

```
kubectl logs hashicorp-consul-connect-injector-webhook-deployment-5d644tzq6l injector-acl-init
Error getting Kubernetes secret: secrets "hashicorp-consul-connect-inject-acl-token" not found
```

### Expected behavior

The init containers to run properly.

### Environment details

If not already included, please provide the following:
- `consul` version: 1.9.1
- `consul-k8s` version: 0.22.0
- `consul-helm` version: consul-0.28.0
- `EKS` version: v1.18.9-eks-d1db3c
- `values.yaml` used to deploy the helm chart:

```
# config.yaml

# Configure global settings in this section.
global:
  domain: consul
  datacenter: primarydc
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
  # Gossip encryption
  gossipEncryption:
    secretName: 'consul-gossip-encryption-key'
    secretKey: 'key'
# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 2
  bootstrapExpect: 2
  storageClass: gp2-encrypted
  # Specify the resources that servers request for placement. These values will serve a large environment.
  resources: |
    requests:
      memory: "32Gi"
      cpu: "4"
    limits:
      memory: "32Gi"
      cpu: "4"

# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  resources: |
    requests:
      memory: "8Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "2"
# Enable and configure the Consul UI.
ui:
  enabled: true
# Configure security for Consul Connect pod injection
connectInject:
  enabled: true
  default: true
  aclBindingRuleSelector: “serviceaccount.name!=default”
controller:
  enabled: true
```

### Additional Context

If I manually create new secrets with the required name and the same content, the init containers run. But then I run into other issues, which I am not sure is related. I see this on the leader pod and helm install times out.
`    2021-01-20T01:11:34.140Z [ERROR] agent.http: Request error: method=PUT url=/v1/acl/binding-rule from=100.64.103.212:50596 error="invalid Binding Rule: Selector is invalid: 1:1 (0): no match found, expected: "(", "-", "0", "\"", "`", "not", [ \t\r\n], [1-9] or [a-zA-Z]"`

A similar error can be seen in the server-acl-init job
`2021-01-20T01:14:19.272Z [ERROR] Failure: creating acl binding rule for hashicorp-consul-k8s-auth-method: err="Unexpected response code: 500 (invalid Binding Rule: Selector is invalid: 1:1 (0): no match found, expected: "(", "-", "0", "\"", "`", "not", [ \t\r\n], [1-9] or [a-zA-Z])"`
