### ISSUE TITLE
Consul and Vault with TLS on Kubernetes

### ISSUE THREAD

**Issue by HofmannZ** [hashicorp/consul-helm#784]
#### Question

We are setting up Consul and Vault on Kubernetes using both of the official Helm charts.
Our goals are:
- to use Consul as a HA backend for Vault.
- use gossip encryption for both Consul and Vault.
- use TLS encryption on client <> server communication.
- use TLS encryption on Vault <> Consul communication.

> NOTE: We would of course first setup ACLs before moving this setup to production.

We have set up our Kubernetes nodes with the labels and taints. And added the affinities, tolerations, and node selectors to the `consul-helm` and `vault-helm` configs. Based on the [Vault on Kubernetes Reference Architecture](https://learn.hashicorp.com/tutorials/vault/kubernetes-reference-architecture?in=vault/kubernetes).

The recommendation from the `consul-helm` is to use auto encrypt for distributing the certificates automatically.

This is our current Consul config:
```yaml
global:
  name: consul
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
  tls:
    enabled: true
    enableAutoEncrypt: true
    serverAdditionalDNSSANs:
    - "consul.service.consul"
    caCert:
      secretName: ca-certs
      secretKey: "ca.crt"
    caKey:
      secretName: ca-certs
      secretKey: "ca.key"
  replicas: 3
server:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: consul
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: "kubernetes.io/hostname"
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: consul
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: "topology.kubernetes.io/zone"
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: vault
              component: server
          topologyKey: "kubernetes.io/hostname"
  tolerations: |
    - key: taint_for_consul_xor_vault
      operator: Equal
      value: "true"
      effect: NoExecute
  nodeSelector: |
    consul_in_k8s: "true"
client:
  tolerations: |
    - key: taint_for_consul_xor_vault
      operator: Equal
      value: "true"
      effect: NoExecute
ui:
  enabled: "-"
  service:
    enabled: false
dns:
  enabled: "-"
ingressGateways:
  enabled: "-"
  gateways:
  - argo-tunnel-example-front-end
```

Our question is: what is the best practice for providing the client TLS certs from Consul to Vault to enforce secure communication between them. We are currently looking into annotating the Vault server pod: `consul.hashicorp.com/connect-inject: "true"`. This would mean Vault would call Consul over localhost and connect-inject would handle the TLS encryption. We wonder though if this is a production-ready approach or just a hacky setup. We also considered providing our own certificates to Consul and Helm via Kubernetes secrets similar to #74.

We really like Consul and Vault's flexibility but are missing a bit for documentation on using both helm charts together. ✌️
