### ISSUE TITLE
CA for terminating gateways

### ISSUE THREAD

**Issue by HofmannZ** [hashicorp/consul-helm#797]
#### Question

Hi 👋,

Having a quick question regarding the terminating gateways.

We have a terminating gateway called `cloudflare-gateway`. We also have an upstream deployment in the mesh listening on the port 80, let's call it `x-server`. We also have a deployment that establishes an SSL encrypted tunnel on port `7844` over TCP. Let's call the deployment `x-proxy`. Both deployments have a sidecar injected by `connectInject`. In addition `x-proxy` defines `x-server` and `cloudflare-gateway` as it's upsteam services using the `consul.hashicorp.com/connect-service-upstreams` annotation. 

Our goal is to have `x-proxy` establish a connection with Argo Tunnel from Cloudflare. To do so, we need to terminate the mesh trough `cloudflare-gateway`. The gateway should respect the SSL tunnel that `x-proxy` has set up. This way we can safely allow traffic into our mesh without opening any additional firewall ports on our VPC. 

consul-helm.yaml
```yaml
global:
  name: consul
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
  tls:
    enabled: true
    enableAutoEncrypt: true

server:
  replicas: 3
  extraConfig: |
    {
      "telemetry": {
        "prometheus_retention_time": "30s"
      },
      "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus",
        "metrics_proxy": {
          "base_url": "http://prometheus-server.service.consul"
        }
      }
    }

client:
  enabled: "-"
  grpc: true

ui:
  enabled: "-"
  service:
    enabled: false

dns:
  enabled: "-"

connectInject:
  enabled: "-"
  default: true
  centralConfig:
    enabled: true
    defaultProtocol: "http"
    proxyDefaults: |
      {
        "envoy_prometheus_bind_addr": "0.0.0.0:9102"
      }

controller:
  enabled: "-"

terminatingGateways:
  enabled: "-"
  gateways:
  - name: cloudflare-gateway
```

x-server.yaml
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: x-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x-server
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-service: "x-server"
      name: x-server
      labels:
        app: x-server
    spec:
      containers:
        - name: x-server
          image: ishustava/http-echo:latest
          command:
          - "/bin/sh"
          - "-ec"
          - |
            /http-echo -listen=:8080 -text="hello world"
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: x-server
```

x-proxy.yaml
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: x-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x-proxy
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-service: "x-proxy"
        consul.hashicorp.com/connect-service-upstreams: "x-server:80,cloudflare-gateway:7844"
      name: x-proxy
      labels:
        app: x-proxy
    spec:
      containers:
        #tunnel container
        ...
      serviceAccountName: x-proxy
```

The problem is that we can't seem to configure the CA for the `terminatingGateway`. Is there anywhere we can find some more docs on it? (Or maybe anyone has a helpful tip 😉)
