### ISSUE TITLE
bootstrapACLs failed to initialize in https

### ISSUE THREAD

**Issue by ram-vibhulaanandh** [hashicorp/consul-helm#815]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

### Overview of the Issue

I'm using the helm deployment of consul. It seems the connection refused errors where because I had enabled TLS encryption and disabled the http port. It works when I leave the http port enabled. How to make consul-server-acl-init in helm config to try connecting with https instead of http?

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
# Configure global settings in this section.
global:
  datacenter: dc1
  enabled: true
  image: "consul:1.9.3"
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
    
  # Gossip encryption
  gossipEncryption:
    secretName: 'consul-gossip-encryption-key'
    secretKey: 'key'
  enablePodSecurityPolicies: true


# Configure your Consul servers in this section.
server:
  enabled: true
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 1
  bootstrapExpect: 1
  storageClass: null
  connect: true
  # Specify the resources that servers request for placement. These values will serve a large environment.
  extraConfig: |
    {
      "log_level": "INFO",
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ca_file": "/consul/userconfig/consul-server-certs/ca.pem",
      "cert_file": "/consul/userconfig/consul-server-certs/consul-server-crt.pem",
      "key_file": "/consul/userconfig/consul-server-certs/consul-server-key.pem",
      "ports": {
        "http": -1,
        "https": 8501
      }
    }

  extraVolumes:
    - type: secret
      name: consul-server-certs
      load: false
    - type: secret
      name: consul-gossip-encryption-key
      load: false


  resources: |
    requests:
      memory: "400Mi"
      #cpu: "0.5"
      #disk: "1Gi"
    limits:
      memory: "500Mi"
      #cpu: "0.5"
      #disk: "1Gi"


  # Prevent Consul servers from co-location on Kubernetes nodes.
  affinity: |
    podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       - labelSelector:
           matchLabels:
             app: {{ template "consul.name" . }}
             release: "{{ .Release.Name }}"
             component: server
         topologyKey: kubernetes.io/hostname
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  grpc: true
  extraConfig: |
    {
      "log_level": "INFO",
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ca_file": "/consul/userconfig/consul-client-certs/ca.pem",
      "cert_file": "/consul/userconfig/consul-client-certs/consul-client-crt.pem",
      "key_file": "/consul/userconfig/consul-client-certs/consul-client-key.pem",
      "ports": {
        "http": -1,
        "https": 8501
      }
    }
  extraVolumes:
    - type: secret
      name: consul-client-certs
      load: false
    - type: secret
      name: consul-gossip-encryption-key
      load: false
  resources: |
    requests:
      memory: "200Mi"
      #cpu: "0.25"
      #disk: "1Gi"
    limits:
      memory: "250Mi"
      #cpu: "0.25"
      #disk: "1Gi"

dns:
  enabled: true
  type: ClusterIP
# Enable and configure the Consul UI.
ui:
  enabled: true
  service:
    enabled: true
    type: NodePort


syncCatalog:
  enabled: true
  default: true
  k8sPrefix: k8s
  k8sAllowNamespaces: ["*"]
  k8sDenyNamespaces: []
  addK8SNamespaceSuffix: true
  k8sTag: k8s
  syncClusterIPServices: true
  logLevel: info
# Configure security for Consul Connect pod injection
connectInject:
  enabled: true
  default: false
  certs:
    secretName: null
    caBundle: ""
    certName: tls.crt
    keyName: tls.key
  aclBindingRuleSelector: "serviceaccount.name!=default"

controller:
  enabled: true

```
1. View error

### Logs

2021-02-09T08:55:44.277Z [INFO]  Retrying in 1s
2021-02-09T08:55:45.360Z [ERROR] Failure: bootstrapping ACLs - PUT /v1/acl/bootstrap: err="Put "http://hashicorp-consul-server-0.hashicorp-consul-server.vault.svc:8500/v1/acl/bootstrap": dial tcp: lookup hashicorp-consul-server-0.hashicorp-consul-server.vault.svc on 10.120.0.10:53: no such host"
2021-02-09T08:55:45.360Z [INFO]  Retrying in 1s
2021-02-09T08:55:46.363Z [ERROR] Failure: bootstrapping ACLs - PUT /v1/acl/bootstrap: err="Put "http://hashicorp-consul-server-0.hashicorp-consul-server.vault.svc:8500/v1/acl/bootstrap": dial tcp: lookup hashicorp-consul-server-0.hashicorp-consul-server.vault.svc on 10.120.0.10:53: no such host"

<details>
  <summary>Logs</summary>

```
output from 'kubectl logs' in relevant components
```

</details>

### Expected behavior

What was the expected result?

### Environment details

If not already included, please provide the following:
- `consul-k8s` version:
- `consul-helm` version: 0.29.0
- `values.yaml` used to deploy the helm chart:

Any other information you can provide about the environment/deployment.

### Additional Context

Additional context on the problem.

**Comment by thisisnotashwin** [comment]
Hey @ram-vibhulaanandh ,

To enable TLS on the consul cluster and also manage ACLs, you will have to populate certain other values in your helm values file. Many of the fields that have been provided to the server and client extraConfig can be provided as helm values as below:
```
# Configure global settings in this section.
global:
  datacenter: dc1
  enabled: true
  image: "consul:1.9.3"
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
  tls:
    # The below config will ensure only the 8501 port is exposed
    enabled: true
    verify: true

    # Consul on Kubernetes manages the TLS server and client certificates.
    # You can provide the CA cert and the CA private key and it will manage
    # certificate generation and management
    caCert:
      secretName: consul-server-certs
      secretKey: ca.pem

  # Gossip encryption
  gossipEncryption:
    secretName: 'consul-gossip-encryption-key'
    secretKey: 'key'
  enablePodSecurityPolicies: true


# Configure your Consul servers in this section.
server:
  enabled: true
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 1
  bootstrapExpect: 1
  storageClass: null
  connect: true
  # Specify the resources that servers request for placement. These values will serve a large environment.
  extraConfig: |
    {
      "log_level": "INFO",
      "ca_file": "/consul/userconfig/consul-server-certs/ca.pem",
      "cert_file": "/consul/userconfig/consul-server-certs/consul-server-crt.pem",
      "key_file": "/consul/userconfig/consul-server-certs/consul-server-key.pem",
    }

  extraVolumes:
  - type: secret
    name: consul-server-certs
    load: false
  - type: secret
    name: consul-gossip-encryption-key
    load: false


  resources: |
    requests:
      memory: "400Mi"
      #cpu: "0.5"
      #disk: "1Gi"
    limits:
      memory: "500Mi"
      #cpu: "0.5"
      #disk: "1Gi"


  # Prevent Consul servers from co-location on Kubernetes nodes.
  affinity: |
    podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       - labelSelector:
           matchLabels:
             app: {{ template "consul.name" . }}
             release: "{{ .Release.Name }}"
             component: server
         topologyKey: kubernetes.io/hostname
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  grpc: true
  extraConfig: |
    {
      "log_level": "INFO",
      "ca_file": "/consul/userconfig/consul-client-certs/ca.pem",
      "cert_file": "/consul/userconfig/consul-client-certs/consul-client-crt.pem",
      "key_file": "/consul/userconfig/consul-client-certs/consul-client-key.pem",
    }
  extraVolumes:
  - type: secret
    name: consul-client-certs
    load: false
  - type: secret
    name: consul-gossip-encryption-key
    load: false
  resources: |
    requests:
      memory: "200Mi"
      #cpu: "0.25"
      #disk: "1Gi"
    limits:
      memory: "250Mi"
      #cpu: "0.25"
      #disk: "1Gi"

dns:
  enabled: true
  type: ClusterIP
# Enable and configure the Consul UI.
ui:
  enabled: true
  service:
    enabled: true
    type: NodePort


syncCatalog:
  enabled: true
  default: true
  k8sPrefix: k8s
  k8sAllowNamespaces: [ "*" ]
  k8sDenyNamespaces: [ ]
  addK8SNamespaceSuffix: true
  k8sTag: k8s
  syncClusterIPServices: true
  logLevel: info
# Configure security for Consul Connect pod injection
connectInject:
  enabled: true
  default: false
  certs:
    secretName: null
    caBundle: ""
    certName: tls.crt
    keyName: tls.key
  aclBindingRuleSelector: "serviceaccount.name!=default"

controller:
  enabled: true

```
