### ISSUE TITLE
Upgrade "consul" failed: post-upgrade hooks failed: timed out waiting for the condition

### ISSUE THREAD

**Issue by mrad-bilel** [hashicorp/consul-helm#835]
### Overview of the Issue

consul upgrade failed 

### Reproduction Steps

1.Upgrade has been done automaticly as i installed consul with Fluxcd helm Operator and referencing master branch:
```
77              Thu Nov 12 19:51:06 2020        failed          consul-0.25.0   1.8.4           Upgrade "consul" failed: post-upgrade hooks failed: timed out waiting for the condition
```
### Environment details

If not already included, please provide the following:
- `consul-k8s` version: EKS v1.16.8
- `consul-helm` version :consul-0.25.0
- `values.yaml` used to deploy the helm chart:
```
  client:
  enabled: true
global:
  acls:
    manageSystemACLs: true
  enablePodSecurityPolicies: true
server:
  bootstrapExpect: 3
  replicas: 3
  storage: 30Gi
ui:
  service:
    type: ClusterIP
```

**Comment by kschoche** [comment]
Hi @mrad-bilel thank you for filing this issue!

It would be really helpful if you could provide a bit more information here so we can try to track down the problem.
You mentioned that you were upgrading consul but I'm not sure what versions of consul you are upgrading from and to.
Could you provide the logs from consul servers that have failed to upgrade?
One other thing that would be helpful is if you could provide a bit more detail on how you're using fluxcd to manage consul?

Thanks!

**Comment by mrad-bilel** [comment]
Hello @kschoche Thanks for the update .

```
Status:
  Conditions:
    Last Transition Time:   2021-01-29T10:55:12Z
    Last Update Time:       2021-02-19T20:22:15Z
    Message:                Chart fetch was successful for Helm release 'consul' in 'consul'.
    Reason:                 ChartFetched
    Status:                 True
    Type:                   ChartFetched
    Last Transition Time:   2020-11-12T19:56:07Z
    Last Update Time:       2021-02-19T20:22:16Z
    Message:                Release failed for Helm release 'consul' in 'consul'.
    Reason:                 Failed
    Status:                 False
    Type:                   Released
  Last Attempted Revision:  572b552d3a25be7bf4211b9ea08e26ac58a95abb
  Observed Generation:      5
  Phase:                    Failed
  Release Name:             consul
  Release Status:           failed
  Revision:                 2f15ed8ab4a8a33924f4b8f082b740417b0dd15f
Events:
  Type     Reason             Age                     From           Message
  ----     ------             ----                    ----           -------
  Warning  FailedReleaseSync  118s (x10286 over 21d)  helm-operator  synchronization of release 'consul' in namespace 'consul' failed: failed to determine sync action for release: status 'failed' of release does not allow a safe upgrade
````
We deployed consul with HelmRelease CRD using Fluxcd

**Comment by mrad-bilel** [comment]
Any update please

**Comment by lkysow** [comment]
Hi @mrad-bilel, we're unfamiliar with this deployment mechanism. Can you please give us step-by-step instructions for how to reproduce?

One thing that I can say is that usually `Upgrade "consul" failed: post-upgrade hooks failed: timed out waiting for the condition` is due to one of the Helm hooks not finishing. I'd look for any pods/jobs that are failing or pending.

**Comment by mrad-bilel** [comment]
@lkysow The recommaned way to install cosul is via a helm chart so insted of doing it manualy i used Fluxcd , values are descrided below


```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: consul
  namespace: consul
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: consul
  chart:
    git: git@github.com:hashicorp/consul-helm
    path: .
    ref: master
  values:
    global:
      acls:
        manageSystemACLs: true
      enablePodSecurityPolicies: true
    client:
      enabled: true
    server:
      replicas: 3
      bootstrapExpect: 3
      storage: 10Gi
    ui:
      service:
        type: ClusterIP
```
