### ISSUE TITLE
keyring api is not working with server.exposeGossipAndRPCPorts and client.exposeGossipAndPorts

### ISSUE THREAD

**Issue by soonoo** [hashicorp/consul-helm#838]
### Reproduction Steps

I installed consul chart with the following `values.yml`.
```
global:
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

server:
  exposeGossipAndRPCPorts: true
  bootstrapExpect: 3
  annotations: |
      "consul.hashicorp.com/service-meta-domain": "http://my-domain.com"
      "consul.hashicorp.com/service-name": "my-consul"
    ports:
        serflan:
            port: 8301
client:
   exposeGossipAndPorts: true

syncCatalog:
    enabled: true
    toConsul: true
    toK8S: true 
    addK8SNamespaceSuffix: false
```

keyring api faile then.
```
$ curl http://my-domain.com/v1/operator/keyring
1 error occurred:
	* dc-name (LAN) error: 0/1 nodes reported success
```

It works with `local-only=true` parameter.
```
$ curl http://my-domain.com/v1/operator/keyring?local-only=true
[{"WAN":false,"Datacenter":"groot-k8s","Segment":"","Keys":{"1asdaasdasdasdasdoKsQNIXE=":15},"PrimaryKeys":{"1asdaasdasdasdasdoKsQNIXE=":15},"NumNodes":15}]
```
### Logs
There is nothing special in error log, it simply says that error occured.

### Environment details

- `consul-k8s` version: latest
- `consul-helm` version: latest
