### ISSUE TITLE
Export -ui-content-path option in value.xaml?

### ISSUE THREAD

**Issue by Rwing** [hashicorp/consul-helm#842]
https://www.consul.io/docs/agent/options#_ui_content_path

It looks like the option ui-content-path cannot be change when using helm now

**Comment by lkysow** [comment]
Hi, I think this was fixed in https://github.com/hashicorp/consul/pull/9569. Are you running a Consul version >= 1.9.2?

**Comment by Rwing** [comment]
Sorry, I probably didn't make myself clear, I meant there is not ui-content-path option in value.xaml, I want to control it to add -ui-content-path option in command line, like this
https://github.com/hashicorp/consul-helm/blob/ae54c22aa2f5e5df057d7f1fff7f4df72fdd7af5/templates/server-statefulset.yaml#L203

**Comment by lkysow** [comment]
You can use the following to set it:

```yaml
server:
  extraConfig: |
    {
       "ui_config": {
         "content_path": "your-path"
       }
    }
```
