### ISSUE TITLE
Error: YAML parse error on consul/templates/server-statefulset.yaml: error converting YAML to JSON: yaml: line 43: did not find expected '-' indicator

### ISSUE THREAD

**Issue by lemonit-eric-mao** [hashicorp/consul-helm#850]
#### Overview of the Issue

K8s helm installation failed

https://learn.hashicorp.com/tutorials/consul/kubernetes-deployment-guide#deploy-consul

#### Reproduction Steps

``` ruby
[root@master01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
[root@master01 ~]#
[root@master01 ~]# helm version
version.BuildInfo{Version:"v3.1.3", GitCommit:"0a9a9a88e8afd6e77337a3e2ad744756e191429a", GitTreeState:"clean", GoVersion:"go1.13.10"}
[root@master01 ~]#
[root@master01 ~]#
[root@master01 ~]# vim config.yaml
[root@master01 ~]#
[root@master01 ~]# helm install -f config.yaml hashicorp hashicorp/consul
coalesce.go:196: warning: cannot overwrite table with non table for resources (map[limits:map[cpu:100m memory:100Mi] requests:map[cpu:100m memory:100Mi]])
coalesce.go:196: warning: cannot overwrite table with non table for resources (map[limits:map[cpu:100m memory:100Mi] requests:map[cpu:100m memory:100Mi]])
Error: YAML parse error on consul/templates/server-statefulset.yaml: error converting YAML to JSON: yaml: line 43: did not find expected '-' indicator
[root@master01 ~]#
[root@master01 ~]#

```

**Comment by david-yu** [comment]
Hi @lemonit-eric-mao could you provide your Helm values file? I suspect some kind of parse/syntax error around the cpu limit and memory configuration, perhaps a whitespace issue?

**Comment by lkysow** [comment]
Hi, it looks like those values in that tutorial are out of date. These should work:
```yaml
# config.yaml

# Configure global settings in this section.
global:
  domain: consul
  datacenter: primarydc
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
  # Gossip encryption
  gossipEncryption:
    secretName: 'consul-gossip-encryption-key'
    secretKey: 'key'
# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 3
  bootstrapExpect: 3
  # Specify the resources that servers request for placement. These values will serve a large environment.
  resources:
    requests:
      memory: "32Gi"
      cpu: "4"
      disk: "50Gi"
    limits:
      memory: "32Gi"
      cpu: "4"
      disk: "50Gi"
  # If using Enterprise, reference the Kubernetes secret that holds your license here
  enterpriseLicense:
    secretName: 'consul-license'
    secretKey: 'key'
  # Prevent Consul servers from co-location on Kubernetes nodes.
  affinity: |
    podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       - labelSelector:
           matchLabels:
             app: {{ template "consul.name" . }}
             release: "{{ .Release.Name }}"
             component: server
         topologyKey: kubernetes.io/hostname
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  resources:
    requests:
      memory: "8Gi"
      cpu: "2"
      disk: "15Gi"
    limits:
      memory: "8Gi"
      cpu: "2"
      disk: "15Gi"
# Enable and configure the Consul UI.
ui:
  enabled: true
# Configure security for Consul Connect pod injection
connectInject:
  enabled: true
  default: true
  aclBindingRuleSelector: "serviceaccount.name!=default"
controller:
  enabled: true
```

We'll update the tutorial.

**Comment by lemonit-eric-mao** [comment]
@lkysow Hello, thank you for your answer. I tried this one config.yaml After that, the following problems still exist. Please help us confirm the reason for the problem
``` ruby

[root@master01 consul]# helm install -f config.yaml hashicorp hashicorp/consul
Error: DaemonSet.apps "hashicorp-consul" is invalid: [spec.template.spec.containers[0].resources.limits[disk]: Invalid value: "disk": must be a standard resource type or fully qualified, spec.template.spec.containers[0].resources.limits[disk]: Invalid value: "disk": must be a standard resource for containers, spec.template.spec.containers[0].resources.requests[disk]: Invalid value: "disk": must be a standard resource type or fully qualified, spec.template.spec.containers[0].resources.requests[disk]: Invalid value: "disk": must be a standard resource for containers]
[root@master01 consul]# 

```

**Comment by ndhanushkodi** [comment]
It looks like `disk` is not configurable via the helm values. (If you want to set storage size for the server see [this](https://www.consul.io/docs/k8s/helm#v-server-storage) helm value). Here's the values @lkysow provided without the disk settings:

```yaml
# config.yaml

# Configure global settings in this section.
global:
  domain: consul
  datacenter: primarydc
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
  # Gossip encryption
  gossipEncryption:
    secretName: 'consul-gossip-encryption-key'
    secretKey: 'key'
# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 3
  bootstrapExpect: 3
  # Specify the resources that servers request for placement. These values will serve a large environment.
  resources:
    requests:
      memory: "32Gi"
      cpu: "4"
    limits:
      memory: "32Gi"
      cpu: "4"
  # If using Enterprise, reference the Kubernetes secret that holds your license here
  enterpriseLicense:
    secretName: 'consul-license'
    secretKey: 'key'
  # Prevent Consul servers from co-location on Kubernetes nodes.
  affinity: |
    podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       - labelSelector:
           matchLabels:
             app: {{ template "consul.name" . }}
             release: "{{ .Release.Name }}"
             component: server
         topologyKey: kubernetes.io/hostname
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  resources:
    requests:
      memory: "8Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "2"
# Enable and configure the Consul UI.
ui:
  enabled: true
# Configure security for Consul Connect pod injection
connectInject:
  enabled: true
  default: true
  aclBindingRuleSelector: "serviceaccount.name!=default"
controller:
  enabled: true
```
