### ISSUE TITLE
setting resources doesn't seem to work

### ISSUE THREAD

**Issue by jipperinbham** [hashicorp/consul-helm#87]
I don't really understand the following change https://github.com/hashicorp/consul-helm/pull/62. the `resources` block is an object and it's using the `tpl` function now which expects a string. What is the expected value to be used to be able to apply something like the following?

```yaml
resources:
  requests:
    memory: "10Gi"
  limits:
    memory: "10Gi"
```

**Comment by adilyse** [comment]
Hi @jipperinbham ,

The best way to define `resources` now is to add a `|` to the definition:
```
resources: |
  requests:
    memory: "10Gi"
  limits:
    memory: "10Gi"
```

This turns the object into a multi-line string. I made the switch because server affinity is defined in this same way and it seemed easier if they worked the same way, but I can see it's still a little confusing! I'll add an example to the documentation to make it more explicit.

Hopefully that helps! Please feel free to reopen the issue if you have further questions.
