### ISSUE TITLE
CORS and GRPC web issue

### ISSUE THREAD

**Issue by Tzvonimir** [hashicorp/consul-helm#879]
Hey everybody,

I have deployed consul on Kubernetes cluster via helm chart, and that part is working exactly as it is supposed to. On top of that, I have enabled Ingress Gateway with connect inject option and deployed my gRPC gateway behind that proxy. When I try to connect to that proxy, It works for everything except gRPC-web(https://github.com/grpc/grpc-web). I am facing a CORS issue now that I can't resolve. So it would be really helpful if someone has any idea how to resolve this issue.

I have configured my local envoy configuration, and It works fine. Here is the local envoy config:

```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: gateway_service
                            max_grpc_timeout: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
  clusters:
    - name: gateway_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 9990

```

Here is my gateway Kubernetes configuration:

ingress gateway:

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: grpc
      services:
        - name: gateway-service
          hosts: 'my-host.com'
```

pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: gateway-service
  labels:
    app: 'gateway-service'
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/connect-service-upstreams: "search-service:9991, reservation-service:9997"
spec:
  containers:
  - name: gateway-service
    image: my.image:latest
    env:
    - name: SERVER_PORT
      value: "9990"
    - name: SERVER_HOST
      value: "127.0.0.1"
    - name: SEARCH_CLIENT_PORT
      value: "9991"
    - name: SEARCH_CLIENT_HOST
      value: "127.0.0.1"
    - name: DEBUG
      value: "true"
    ports:
    - containerPort: 9990
      name: grpc
  imagePullSecrets:
  - name: gitlab-auth
  serviceAccountName: gateway-service

```

service:

```
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP
  selector:
    app: gateway-service
  ports:
  - name: grpc
    port: 9990
    targetPort: 9990

```

service account:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service

```

service defaults:

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: gateway-service
spec:
  protocol: grpc
```

As much as I was able to understand from documentation and some other issues I have to add **ProxyDefaults** kind and `envoy_extra_static_listeners_json`. And I have tried to do so, but nothing has worked for me, here is the example of config I tried:

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: ingress-gateway
spec:
  config:
    protocol: grpc
    envoy_extra_static_listeners_json: '{"name":"listener_0","address":{"socket_address":{"address":"my-host.com","port_value":8080}},"filter_chains":[{"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"@type":"type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager","codec_type":"auto","stat_prefix":"ingress_http","route_config":{"name":"local_route","virtual_hosts":[{"name":"local_service","domains":["*"],"routes":[{"match":{"prefix":"/"},"route":{"cluster":"gateway_service","max_grpc_timeout":"0s"}}],"cors":{"allow_origin_string_match":[{"prefix":"*"}],"allow_methods":"GET, PUT, DELETE, POST, OPTIONS","allow_headers":"keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout","max_age":"1728000","expose_headers":"custom-header-1,grpc-status,grpc-message"}}]},"http_filters":[{"name":"envoy.filters.http.grpc_web"},{"name":"envoy.filters.http.cors"},{"name":"envoy.filters.http.router"}]}}]}]}'

```

Thanks.

**Comment by lkysow** [comment]
Hi @Tzvonimir, sorry to hear you're having this issue.

I just tried to get things set up but I think I'm missing things like your helm values file and the Docker image for the gateway (`image: my.image:latest`) and also the search and reservation services.

Can you supply us with simple step by step instructions on how to reproduce this ourselves? In addition can you supply the CORS error you're getting? Thanks!

**Comment by Tzvonimir** [comment]
@lkysow thank you for replying. 

here is my consul helm chart values file:

```yaml

global:
  name: consul
  enabled: true
  datacenter: ${datacenter_name}

  gossipEncryption:
    secretName: "consul-gossip-key"
    secretKey: "key"

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

  # Vault chart not working with acls enabled
  #acls:
    #manageSystemACLs: true

server:
  replicas: ${replicas}
  bootstrapExpect: ${replicas}
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  extraConfig: |
    {
      "telemetry": {
        "prometheus_retention_time": "10s"
      },
      "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus",
        "metrics_proxy": {
          "base_url": "http://prometheus-server"
        }
      }
    }

client:
  enabled: true
  # enable gRPC on your client to support Consul service mesh
  grpc: true

ui:
  enabled: true

connectInject:
  #aclBindingRuleSelector: ""
  enabled: true
  grpc: true
  # inject an envoy sidecar into every new pod, except for those with annotations that prevent injection
  default: true
  # these settings enable L7 metrics collection and are new in 1.5
  centralConfig:
    enabled: true
    # set the default protocol (can be overwritten with annotations)
    defaultProtocol: 'http'
    # proxyDefaults is a raw json string that will be applied to all Connect
    # proxy sidecar pods that can include any valid configuration for the
    # configured proxy.
    proxyDefaults: |
      {
        "envoy_prometheus_bind_addr": "0.0.0.0:9102"
      }

controller:
  enabled: true
ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer

```

More high level look into architecture:

- AWS cluster on EKS running consul and vault (+prometheus and grafana)

- After deploying the cluster I am deploying multiple Kubernetes microservices in private subnet (Most of them are written in go and only one is in java), but only one is important, and that one is a "gateway" service. Because everything has to pass through "gateway"

- Ingress gateway is running in public subnet and is exposed to "external internet".

Currently, everything is deployed and working. iOS, Android, and backend developers can access it without a problem. They are making GRPC calls and getting response back. 

But when we try to access it via browser using GRPC web we can't do it. (Request is blocked somewhere on ingress gateway, it is not able to reach our "gateway") 

We tried to setup envoy proxy locally with custom CORS and HTTP to GRPC conversion and it is working perfectly.

Here is the local envoy config that we are using to test our GRPC-web calls.

```yaml

admin:
  access_log_path: /dev/stdout
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: gateway_service
                            max_grpc_timeout: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
  clusters:
    - name: gateway_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 9990


```

So for this question:

`my.image:latest` is an image hosted on a private repository (unfortunately I am not able to share access to that because of company policy. But you can use any GRPC server running an insecure connection for testing. If you do not want to lose your time to set up the GRPC server, I will create a simple gateway project with the GRPC server and deploy the docker image to the public hub (and update config accordingly, but again the problem is somewhere on ingress gateway, envoy config is probably not structured correctly).

```yaml

apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: ingress-gateway
spec:
  config:
    protocol: grpc
    envoy_extra_static_listeners_json: '{"name":"listener_0","address":{"socket_address":{"address":"my-host.com","port_value":8080}},"filter_chains":[{"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"@type":"type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager","codec_type":"auto","stat_prefix":"ingress_http","route_config":{"name":"local_route","virtual_hosts":[{"name":"local_service","domains":["*"],"routes":[{"match":{"prefix":"/"},"route":{"cluster":"gateway_service","max_grpc_timeout":"0s"}}],"cors":{"allow_origin_string_match":[{"prefix":"*"}],"allow_methods":"GET, PUT, DELETE, POST, OPTIONS","allow_headers":"keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout","max_age":"1728000","expose_headers":"custom-header-1,grpc-status,grpc-message"}}]},"http_filters":[{"name":"envoy.filters.http.grpc_web"},{"name":"envoy.filters.http.cors"},{"name":"envoy.filters.http.router"}]}}]}]}'

```
CORS error:

```
Access to XMLHttpRequest at 'http://gateway.web.elude.co:8080/elude.proto.GatewayController/RunSearch' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

```

When I disable CORS in the browser I get the following error:
```
upstream connect error or disconnect/reset before headers. reset reason: remote reset
```

Thank you for your time. I am grateful for all the help that you guys can give :)
