### ISSUE TITLE
add optional ingress resource

### ISSUE THREAD

**Issue by msarmstr** [hashicorp/consul-helm#88]
It would be nice if an ingress resource could optionally be configured for the ui, ideally with ability to configure labels, annotations, and TLS.

For example: [how it's done in the prometheus-operator chart](https://github.com/helm/charts/blob/d18382c23dbe20d668a9af908604056866895e99/stable/prometheus-operator/templates/prometheus/ingress.yaml)

**Comment by adilyse** [comment]
Hi @msarmstr,

We're still sorting out how Ingresses interact with Consul in Kubernetes, so I don't have a full answer for you. However, I just merged #105 that should allow a fair amount of flexibility in providing additional ways to configure the UI service to be accessed.

**Comment by botzill** [comment]
Hi.

Any updates  on this issues?

**Comment by carpenike** [comment]
@adilyse -- looks like those changes enable annotations on a service, not the creation of an ingress object.

Suggest referencing a solution such as the one used by Minio:

https://github.com/helm/charts/blob/master/stable/minio/templates/ingress.yaml

This would allow for an ingress object to be created if the value is set. The actual ingress object is farily simple, mine is here:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul
  namespace: kube-system
  labels:
    app.kubernetes.io/name: consul
spec:
  rules:
  - host: consul.DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: consul-consul-ui
          servicePort: 80

```

I can pull together a PR if you guys would be willing to review it.
