### ISSUE TITLE
consul-server statefulsets do not start properly when using consul:1.7.2

### ISSUE THREAD

**Issue by soonoo** [hashicorp/consul-helm#890]
Hi
It seems specific version of consul image(`1.7.2` in my case) is not compatible with the latest release of consul-helm(`0.31.1`).
`consul:1.9.4` works well with `consul-helm 0.31.1` however.
 
`values.yml`:
```
global:
  image: consul:1.7.2
  imageK8S: consul-k8s:0.25.0
  acls:
    manageSystemACLs: true

server:
  enabled: true
  exposeGossipAndRPCPorts: true
  replicas: 3
  bootstrapExpect: 3

client:
  enabled: true
  exposeGossipPorts: true
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 200m
      memory: 500Mi

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  addK8SNamespaceSuffix: false

ui:
  enabled: true
  service:
    type: NodePort
```
### Logs

```
$ kubectl logs pods/consul-server-0
==> Error parsing /consul/config/..2021_04_01_10_06_09.075240085/ui-config.json: 1 error occurred:
	* invalid config key ui_config
```

If not already included, please provide the following:
- `consul-k8s` version: 0.25.0
- `consul-helm` version: 0.31.1
- `consul` version: 1.7.2

Additionally, please provide details regarding the Kubernetes Infrastructure, if known:
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): self hosted
- Networking CNI plugin in use: cilium

Any other information you can provide about the environment/deployment.
