### ISSUE TITLE
[0.32.0-beta1] container's runAsUser breaks non-root policy

### ISSUE THREAD

**Issue by HofmannZ** [hashicorp/consul-helm#918]
### Overview of the Issue

The `consul-connect-inject-init` container does not follow non-root policy.

### Reproduction Steps

Steps to reproduce this issue:

1. When running helm install with the following `values.yml`:
```
global:
  name: consul
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
  tls:
    enabled: true
    enableAutoEncrypt: true
    serverAdditionalDNSSANs:
    - "consul.service.consul"
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true

server:
  replicas: 3
  storageClass: premium-rwo
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      cpu: "1"
      memory: 4Gi
  extraConfig: |
    {
      "telemetry": {
        "prometheus_retention_time": "60s"
      },
      "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus",
        "metrics_proxy": {
          "base_url": "http://prometheus-server"
        },
        "dashboard_url_templates": {
          "service": {{`"https://etp-grafana-dev.zino-hofmann.com/d/etp/service-overview?orgId=1&var-service={{Service.Name}}&var-namespace={{Service.Namespace}}&var-dc={{Datacenter}}"`}}
        }
      }
    }
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: consul
              release: consul
              component: server
          topologyKey: "kubernetes.io/hostname"
  tolerations: |
    - key: taint_for_consul_xor_vault
      operator: Equal
      value: "true"
      effect: NoExecute
  nodeSelector: |
    consul_in_k8s: "true"

client:
  enabled: true
  grpc: true
  tolerations: |
    - key: taint_for_consul_xor_vault
      operator: Equal
      value: "true"
      effect: NoExecute

ui:
  enabled: true
  service:
    enabled: false

dns:
  enabled: true

connectInject:
  enabled: true
  default: true
  tolerations: |
    - key: taint_for_consul_xor_vault
      operator: Equal
      value: "true"
      effect: NoExecute
  nodeSelector: |
    consul_in_k8s: "true"
  sidecarProxy:
    resources:
      requests:
        memory: 25Mi
        cpu: 20m
      limits:
        memory: 50Mi
        cpu: 20m

controller:
  enabled: true
  replicas: 2
  tolerations: |
    - key: taint_for_consul_xor_vault
      operator: Equal
      value: "true"
      effect: NoExecute
  nodeSelector: |
    consul_in_k8s: "true"

terminatingGateways:
  enabled: true
  gateways:
  - name: default-gateway
```
1. The `consul-connect-inject-init` container's fails with:

```
container's runAsUser breaks non-root policy (pod: "prometheus-server-0_etp(ac4c04b7-df19-4138-84a0-47bdcad32cc8)", container: consul-connect-inject-init): CreateContainerConfigError
```

### Logs

<details>
  <summary>Logs</summary>

```
container's runAsUser breaks non-root policy (pod: "prometheus-server-0_etp(ac4c04b7-df19-4138-84a0-47bdcad32cc8)", container: consul-connect-inject-init): CreateContainerConfigError
```

</details>

### Expected behavior

What was the expected result?

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: hashicorp/consul-k8s:0.26.0-beta1
- `consul-helm` version: 0.32.0-beta1
- `values.yaml` used to deploy the helm chart: see above

Additionally, please provide details regarding the Kubernetes Infrastructure, if known:
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): GKE (K8s version 1.20.5-gke.800)
- Networking CNI plugin in use: default
