### ISSUE TITLE
Can't connect to terminating gateway

### ISSUE THREAD

**Issue by rmgpinto** [hashicorp/consul-helm#923]
### Overview of the Issue

I'm trying to connect to the `consul-ui` kubernetes service via `ingress-gateway` + `terminating gateway`.
I've setup the `ingress-gateway` and the `static-server` from the examples for testing and it's working correctly.
```
$ curl https://static-server.<my_dns_domain>
"hello world"
```

Now I'm trying to expose the `consul-ui` service and I'm getting this error:
`upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`

I believe this is due to the `terminating gateway` trying to validate a self-signed certificate from the `consul-ui`.

The `consul-ui` kubernetes service appears on Consul catalog as `consul-ui-consul`.

`$ kubectl apply -f consul-ui.yaml`

consul-ui.yaml
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: consul
spec:
  listeners:
    - port: 443
      protocol: http
      services:
        - name: static-server
          hosts: ["static-server.<my_dns_domain>"]
        - name: consul-ui-consul
          hosts: ["consul.<my_dns_domain>"]
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
  namespace: consul
spec:
  services:
    - name: consul-ui-consul
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: consul-ui-consul
  namespace: consul
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: consul-ui-consul
  namespace: consul
spec:
  destination:
    name: consul-ui-consul
  sources:
    - name: ingress-gateway
      action: allow
```

### Reproduction Steps

Steps to reproduce this issue, eg:
1. When running helm install with the following `values.yml`:
```
global:
  name: consul
  image: "hashicorp/consul:1.9.5"
  tls:
    enabled: true
    enableAutoEncrypt: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
server:
  replicas: 3
ui:
  service:
    annotations: |
      "consul.hashicorp.com/service-sync": "true"
  metrics:
    baseURL: http://prometheus-server.prometheus
syncCatalog:
  enabled: true
  default: false
connectInject:
  enabled: true
  default: true
  namespaceSelector: |
    matchLabels:
      "consul.hashicorp.com/connect-inject": "true"
controller:
  enabled: true
ingressGateways:
  enabled: true
  defaults:
    replicas: 2
    service:
      type: LoadBalancer
      ports:
        - port: 443
          nodePort: null
      annotations: |
        external-dns.alpha.kubernetes.io/hostname: <my_dns_domain>
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert:<my_ssl_cert_arn>
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  gateways:
    - name: ingress-gateway
terminatingGateways:
  enabled: true
  defaults:
    replicas: 2
  gateways:
    - name: terminating-gateway
```
1. View error

### Logs

Logs don't show anything relevant.

<details>
  <summary>Logs</summary>

```
output from 'kubectl logs' in relevant components
```

</details>

### Expected behavior

What was the expected result?

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: 1.9.5
- `consul-helm` version: 0.31.1
- `values.yaml` used to deploy the helm chart: pasted above
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): AWS EKS 1.19
