### ISSUE TITLE
server.exposeGossipAndRPCPorts: true doesnt work on openshift (okd v4)

### ISSUE THREAD

**Issue by JarleB** [hashicorp/consul-helm#932]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

### Overview of the Issue
Consul server pods  are unable to start because the consul server is not allowed (SCC-violation) to open the necessary hostPorts 

### Reproduction Steps

Turn on  exposeGossipAndRPCPorts in server-values. It will try to open host ports on server pods, however this is not allowed and hence server pods never start

The relevant values triggering the problem is  :
```
server:
  exposeGossipAndRPCPorts: true
  ports:
    serflan:
      port: 9301
```
1. View error

### Logs

`oc get events` in consul namespace(project) states that no SCC found allowing server pods to open hostPorts

### Expected behavior

SErver pods starts with GossipAndRPCPorts exposed

### Environment details
Self hosted openshift (okd) 

oc version 
Client Version: 4.6.0-0.okd-2021-01-23-132511
Server Version: 4.6.0-0.okd-2021-01-23-132511
Kubernetes Version: v1.19.2-1023+4cad5caeae67c3-dirty

If not already included, please provide the following:
- `consul-k8s` version: 1.9.4
- `consul-helm` version: 0.31.1
- `values.yaml` used to deploy the helm chart: 

Additionally, please provide details regarding the Kubernetes Infrastructure, if known:
- Cloud Provider (If self-hosted, the Kubernetes provider utilized):
- Networking CNI plugin in use:

Any other information you can provide about the environment/deployment.

### Additional Context
The problem is solved by adding the following to the `rules` section of server-role.yaml
```
{{- if .Values.global.openshift.enabled}}
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames:
  - {{ template "consul.fullname" . }}-client
  verbs:
  - use
{{- end}}
```
This will make the chart apply the client scc to the server too if openshift is enabled. It might not be the correct solution but it technically solves the problem.  I can make a PR with this fix if you wish, or please advise.

**Comment by kschoche** [comment]
Hi @JarleB! Thanks for filing this issue!
I'm trying to understand how you're running into this problem but it's not clear to me yet. Could you attach your whole custom val.yaml file so I could take a look? It looks like if we need to add this SCC rule it could be done but I'd like to see it scoped down so that it's only added in the cases where it's required, such as for example when exposeGossipAndRPCPorts are enabled?

We always love to have community contributions, so if we can just get a better idea of whats going on first here then it's probably a pretty straightforward fix that you could send in if you choose!
Thanks!

**Comment by JarleB** [comment]
Agreed the extra SCC should be scoped down to `server.exposeGossipAndRPCPorts: true` AND `global.openshift.enabled: true` 

Here is the complete values file a jinja2 tamplate the just renders in the correct datacenter name:

```
global:
  enablePodSecurityPolicies: true
  name: consul
  datacenter: {{cluster_type}}-{{okd_cluster_name}}
  acls:
    manageSystemACLs: true
    createReplicationToken: true
  tls:
    enabled: true
  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
  openshift:
    enabled: true
server:
  exposeGossipAndRPCPorts: true
  ports:
    serflan:
      port: 9301
client:
  exposeGossipPorts: true
  tolerations: |
    - operator: Exists
connectInject:
  enabled: true
terminatingGateways:
  enabled: true
  defaults:
    extraVolumes:
      - type: 'secret'
        name: 'logstash-tgw-certs'
        items: # optional items array
          - key: tls.key
            path: tls.key
          - key: tls.crt
            path: tls.crt
```
