### ISSUE TITLE
Enabling metrics and TLS results in strange behaviour

### ISSUE THREAD

**Issue by mariusehr1** [hashicorp/consul-helm#935]
Hello,

I am experiencing an issue while trying to expose prometheus metrics of my agents in a Consul instance deployed on EKS.

I had to delete some checks related checks in order to make it work  in `templates/server-statefulset.yaml` and in `templates/client-daemonset.yaml`  : 

```
{{- if (and (and .Values.global.tls.enabled .Values.global.tls.httpsOnly) (and .Values.global.metrics.enabled .Values.global.metrics.enableAgentMetrics))}}{{ fail "global.metrics.enableAgentMetrics cannot be enabled if TLS (HTTPS only) is enabled" }}{{ end -}}
```

The message here is misleading as it makes you think that it will work if you remove `httpsOnly` but it won't as it is checking for `tls.enabled` all together.

Removing those two checks and using the following values DOES work

```
global:
[...]
  metrics:
    agentMetricsRetentionTime: 1m
    enableAgentMetrics: true
    enableGatewayMetrics: true
    enabled: true
  name: consul
  tls:
    caCert:
      secretKey: tls.crt
      secretName: consul-ca-cert
    caKey:
      secretKey: tls.key
      secretName: consul-ca-key
    enableAutoEncrypt: true
    enabled: true
[...]
```

Removing TLS all together (without changing the manifests) does not work as Its mandatory for federation (plus I don't want to drop it for obvious security reasons)

I am also wondering something : no matter if the `metrics` flag is enabled , metrics will still be available at `/v1/agent/metrics` but `/v1/agent/metrics?format=prometheus`  will result in `Prometheus is not enabled since its retention time is not positive` , could you elaborate on that behaviour?

I am pretty sure you guys are working on those features for next releases but I would like to know if my configuration brings any side effect that I should be aware of.

Thanks
Marius

**Comment by kschoche** [comment]
Hi @mariusehr1 !  Thanks for filing this issue, I can confirm that with the values you mentioned in the ticket that we do run into this check failing. This check is in place because prometheus does not support pull stats over TLS by default when configured using annotations.
 
As for the core problem that you reported on the checks, I'm not able reproduce it failing when including `tls.httpsOnly: false`, I'm wondering if maybe you put that entry in the wrong stanza, or had a typo?
```
kyle@kyles-mbp test_hc % cat ../test_community/metrics/val.yaml
global:
  enabled: true
  metrics:
    agentMetricsRetentionTime: 1m
    enableAgentMetrics: true
    enableGatewayMetrics: true
    enabled: true
  name: kyle-consul
  tls:
    httpsOnly: false
    caCert:
      secretKey: tls.crt
      secretName: consul-ca-cert
    caKey:
      secretKey: tls.key
      secretName: consul-ca-key
    enableAutoEncrypt: true
    enabled: true
```

Just to be sure, could you attach your whole val.yaml where it was failing the checks with `httpsOnly: false` , and also confirm which release you're using?

Thanks!
