### ISSUE TITLE
How should it be configured to enable Access-Control-Allow-Origin?

### ISSUE THREAD

**Issue by Shige99011** [hashicorp/consul-helm#946]
Hi, I'm using Ingress gateway to make it access from an external service that is simple javascript application. When an API that is in consul service mesh is called via Ingress gateway, an error like below happens:

`Access to fetch at 'http://192.168.202.199:31000/hello-service/hello' from origin 'http://localhost:9020' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

How should it be configured to enable Access-Control-Allow-Origin for Ingress gateway?
btw, the API responses correctly when it is called by using curl command like:
`curl -H "Host: api-service.ingress.consul" "http://<ip address of the node>:31000/hello-service/hello" `

**My environment is below:**
OS: ubuntu 18.04 on hyper-v
microk8s: v1.20.5
kubernetes: v1.20.5
consul: v1.9.4
Consul helm chart: v0.31.1
(Consul helm chart was installed by command "microk8s helm3 install -f config.yaml consul hashicorp/consul --version "0.31.1"")
There is only one kubernetes node.

**The description of my ingress gateway object:**
```
Name:         ingress-gateway
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  consul.hashicorp.com/v1alpha1
Kind:         IngressGateway
Metadata:
  Creation Timestamp:  2021-05-07T05:22:28Z
  Finalizers:
    finalizers.consul.hashicorp.com
  Generation:  4
  Managed Fields:
    API Version:  consul.hashicorp.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.consul.hashicorp.com":
      f:spec:
        f:tls:
          .:
          f:enabled:
      f:status:
        .:
        f:conditions:
        f:lastSyncedTime:
    Manager:      consul-k8s
    Operation:    Update
    Time:         2021-05-07T05:22:28Z
    API Version:  consul.hashicorp.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:listeners:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-05-07T05:22:28Z
  Resource Version:  2996629
  Self Link:         /apis/consul.hashicorp.com/v1alpha1/namespaces/default/ingressgateways/ingress-gateway
  UID:               64506060-8217-4568-b74e-6221786ce80f
Spec:
  Listeners:
    Port:      7000
    Protocol:  http
    Services:
      Name:  api-service
  Tls:
    Enabled:  false
Status:
  Conditions:
    Last Transition Time:  2021-05-07T05:40:10Z
    Status:                True
    Type:                  Synced
  Last Synced Time:        2021-05-07T05:40:10Z
Events:                    <none>
```

**The configured values.yaml of Conul helm chart is**
```
global:
  name: consul

server:
  replicas: 1
client:
  enabled: true
connectInject:
  enabled: true
controller:
  enabled: true
  
terminatingGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: terminating-gateway

ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: NodePort
        ports:
          - port: 7000
            nodePort: 31000
```

Thanks for your help.
