### ISSUE TITLE
Consul HA on K8S cluster

### ISSUE THREAD

**Issue by mateusdemboski** [hashicorp/consul-helm#949]
I'm running a POC that consists in deploy consul in a k8s cluster for HA. But, I figured out that service registering is randomly registered in each server in the cluster. So, what happens if one of the clusters fails? there is any way to sync servers or is it just a mistake in my helm config?

![image](https://user-images.githubusercontent.com/2401670/117731451-851e6480-b1c4-11eb-9acd-4b60ea46e806.png)

this is my consul deploy config:
```yaml
global:
  name: consul
  datacenter: "MY-DC"
  # Gossip encryption
  gossipEncryption:
    secretName: 'consul-gossip-encryption-key'
    secretKey: 'key'
  acls:
    manageSystemACLs: true
server:
  replicas: 3
  bootstrapExpect: 3
client:
  enabled: true
ui:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: consul.mydomain.com
    tls:
      - hosts:
        - consul.mydomain.com
        secretName: mydomaincom
```
