### ISSUE TITLE
How configure Ingress gateway with the type of ClusterIP?

### ISSUE THREAD

**Issue by Shige99011** [hashicorp/consul-helm#959]
Hi, I would like to configure ingress gateway with ClusterIP to allow only access from inside of the node.
When I tried with NodePort, it worked fine. However it returns 404 not found with ClusterIP.

The values.yaml is:

```
global:
  name: consul
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"
    enableGatewayMetrics: true

server:
  replicas: 1
client:
  enabled: true
connectInject:
  enabled: true
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultPrometheusScrapePort: 20200
    defaultPrometheusScrapePath: "/metrics"


ui:
  enabled: true
  metrics:
    enabled: true # by default, this inherits from the value global.metrics.enabled
    provider: "prometheus"
    baseURL: http://prometheus-server

controller:
  enabled: true
  
terminatingGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: terminating-gateway

ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
  - name: ingress-gateway
    service:
      type: ClusterIP

prometheus:
  enabled: true
grafana:
  enabled: true

```
The manifest for Ingress gateway is:

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: api-service
```
The manifest for ServiceDefault is:

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: api-service
spec:
  protocol: http
```

The api-service is:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service
---
apiVersion: v1
kind: Pod
metadata:
  name: api-service
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
spec:
  containers:
    - name: api-service
      image: api-service:alpha5
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 10000
          name: http
      env:
        - name: 'LISTEN_PORT'
          value: '10000'
    # If ACLs are enabled, the serviceAccountName must match the Consul service name.
  serviceAccountName: api-service

```

The services are:
```
NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                   AGE
kubernetes                    ClusterIP   10.152.183.1     <none>        443/TCP                                                                   35d
frontend-nodeport             NodePort    10.152.183.64    <none>        80:30080/TCP                                                              24h
consul-server                 ClusterIP   None             <none>        8500/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   30m
consul-ui                     ClusterIP   10.152.183.47    <none>        80/TCP                                                                    30m
consul-connect-injector-svc   ClusterIP   10.152.183.41    <none>        443/TCP                                                                   30m
consul-controller-webhook     ClusterIP   10.152.183.35    <none>        443/TCP                                                                   30m
consul-dns                    ClusterIP   10.152.183.102   <none>        53/TCP,53/UDP                                                             30m
grafana                       ClusterIP   10.152.183.157   <none>        3000/TCP                                                                  30m
consul-ingress-gateway        ClusterIP   10.152.183.98    <none>        8080/TCP,8443/TCP                                                         30m
prometheus-server             ClusterIP   10.152.183.170   <none>        80/TCP                                                                    30m
```

Then, I tried curl command from any pod that is outside of service mesh in the node:
curl -H "Host: api-service.ingress.consul" "http://10.152.183.98:8080/hello"
But it returns 404 not found like:
```
*   Trying 10.152.183.98:8080...
* Connected to 10.152.183.98 (10.152.183.98) port 8080 (#0)
> GET /hello HTTP/1.1
> Host: api-service.ingress.consul
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Thu, 20 May 2021 05:23:13 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host 10.152.183.98 left intact
```
What configuration or command execution is wrong?

My enviroment is:
```
OS: ubuntu 18.04 on hyper-v
microk8s: v1.20.5
kubernetes: v1.20.5
consul: v1.9.4
Consul helm chart: v0.31.1
(Consul helm chart was installed by command "microk8s helm3 install -f config.yaml consul hashicorp/consul --version "0.31.1"")
There is only one kubernetes node.
```

Thanks for your any help.

**Comment by Shige99011** [comment]
It has worked finally after the change of ingressgateway configuration on values.yaml like below:

```
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
    service:
      type: ClusterIP
  gateways:
  - name: ingress-gateway
```
Ingress gateway returns expected response for the below request from outside of the service mesh in the node:
`curl -H "Host: api-servicve.ingress.consul" "http://consul-ingress-gateway:8080/hello"`
