### ISSUE TITLE
Failover feature ACL not found, even if we have all the tokens and ACL enabled with global management policy

### ISSUE THREAD

**Issue by BrontesGiga** [hashicorp/consul-helm#967]
We are trying to implement the failover feature of consul with two federated consul datacenters using a Helm chart in AWS-EKS. In the Helm chart we have basic configuration as the consul documentation suggest. The following is our helm chart file for the primary datacenter.
```
global:
  name: consul
  datacenter: consul-eks-primary
  tls:
    enabled: true
    enableAutoEncrypt: true
  federation:
    enabled: true
    createFederationSecret: true
  acls:
    manageSystemACLs: false
    createReplicationToken: true
  gossipEncryption:
    secretName: consul-gossip
    secretKey: gossipEncryptionKey
connectInject:
  enabled: true
controller:
  enabled: true
ui:
  service:
    type: LoadBalancer
meshGateway:
  enabled: true

dns:
  enabled: true
server:
  extraConfig: |
    {
      "log_level": "DEBUG"
    } 
```
This is for the secondary datacenter
```
global:
  name: consul
  datacenter: consul-eks-secondary
  tls:
    enabled: true
    #verify: false
    enableAutoEncrypt: true
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey
  acls:
    manageSystemACLs: true
    replicationToken:
      secretName: consul-federation
      secretKey: replicationToken
  federation:
    enabled: true
  gossipEncryption:
    secretName: consul-federation
    secretKey: gossipEncryptionKey
connectInject:
  enabled: true
controller:
  enabled: true
ui:
  service:
    type: LoadBalancer
meshGateway:
  enabled: true
server:
  # Here we're including the server config exported from the primary
  # via the federation secret. This config includes the addresses of
  # the primary datacenter's mesh gateways so Consul can begin federation.
  extraVolumes:
    - type: secret
      name: consul-federation
      items:
        - key: serverConfigJSON
          path: config.json
      load: true
  extraConfig: |
    {
      "log_level": "DEBUG"
    }
```
To deploy helm chart we are using `helm install consul hashicorp/consul -f consul-helm/values.yaml -n consul`

The error that appears is the following:
`agent.server.rpc: RPC failed to server in DC: server=${server-ip} datacenter=consul-eks-secondary method=PreparedQuery.ExecuteRemote error="rpc error making call: ACL not found"
`
We understand this is an error related to consul policies, but we already have global management policy attached to all tokens. we believe is an error inside of the networking progress helm is building. 
we'll be pleased pasting here any kind of logs to show any king of information you need.
