### ISSUE TITLE
Attaching AWS ACM Certificate to Consule UI Service

### ISSUE THREAD

**Issue by oguzhanaygn** [hashicorp/consul-helm#968]
Hi, I'm a newbie on Consul. I'm following (https://learn.hashicorp.com/tutorials/consul/kubernetes-eks-aws) this guideline to deploy Consul to my AWS EKS Cluster with Helm. I want to use my own ACM certificate for this process. My values.yml ;

```
global:
  enabled: true
  datacenter: xxx
  image: "hashicorp/consul:1.9.5"
  tls:
    enabled: true
    enableAutoEncrypt: true
    httpsOnly: true

ui:
  service:
    type: 'LoadBalancer'
    annotations: |
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xxxxxxxxxxx

```
With this configuration, when I try to reach Consul UI via browser, I'm getting **Client sent an HTTP request to an HTTPS server.** error. Is making this configuration work impossible? Are ingress gateways really needed for SSL termination?
