### ISSUE TITLE
Federation failed in IPv6-only Kubernetes cluster

### ISSUE THREAD

**Issue by OpenetCK** [hashicorp/consul-helm#969]
### Overview of the Issue

In the IPv6-only cluster, the HOST_IP is resolved to for example `fc00:f853:ccd:e793::2`.

Components such as mesh-gateway, connect-injector-webhook are not working because the environment variable of the containers mapped to the following:
```
          env:
            - name: CONSUL_HTTP_ADDR
              value: https://$(HOST_IP):8501
```

This leads to the error during the Consul startup:
```
Invalid Consul HTTP address: address fc00:f853:ccd:e793::2:8501: too many colons in address
```

### Reproduction Steps

Install via Consul Helm chart in a IPv6 only cluster with federation enabled. For example the values file below are used
```
global:
  tls:
    enabled: true

  federation:
    enabled: true
    createFederationSecret: true

  acls:
    manageSystemACLs: true
    createReplicationToken: true

  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

connectInject:
  enabled: true

meshGateway:
  enabled: true
  replicas: 1
```

### Logs

```
Invalid Consul HTTP address: address fc00:f853:ccd:e793::2:8501: too many colons in address
```

### Expected behavior

Able to install Consul in IPv6-only cluster

### Environment details

- `consul-k8s` version: 0.25.0
- `consul-helm` version: 0.31.1
