### ISSUE TITLE
How route traffic to another consul node?

### ISSUE THREAD

**Issue by Shige99011** [hashicorp/consul-helm#970]
There are two consul clusters and each cluster is on a kubernetes node. Only one cluster (Node A) has consul server and another one(Node B) is just joining to the server's cluster.
Node A has ingress gateway and a service to route the traffic to other services. Then I would like to route the traffic to a service which is running on Node B beyond Node A. All services for each node have been configured with sidecar proxy.

In this case, how should the servicerouter manifest be configured? or any other configurations (e.g. Mesh gateway..etc?)are needed?
My current manifest for ServiceRouter:

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api-service
spec:
  routes:
    - match:
        http:
          pathPrefix: "/hello-service" 
      destination:
        service: "hello-service" # This service is in Node A.
    - match:
        http:
          pathPrefix: "/hola-service"
      destination:
        service: "hola-service" # This service is in Node B.

```
Currently the response for curl command from inside of Node A to the service in Node B (curl -H "Host: api-service.ingress.consul" "http://consul-ingress-gateway:8080/hola-service/hola" ) is:
`upstream connect error or disconnect/reset before headers. reset reason: local reset`
But the curl command for the service in Node A returns correctly.
Btw, all services are indicated as healthy on Consul UI.

My environment is:
```
OS: ubuntu 18.04 on hyper-v
microk8s: v1.20.5
kubernetes: v1.20.5
consul: v1.9.4
Consul helm chart: v0.31.1
(Consul helm chart was installed by command "microk8s helm3 install -f config.yaml consul hashicorp/consul --version "0.31.1"")
There are two kubernetes nodes on same LAN.
```

Thanks for your any help.
