### ISSUE TITLE
Consul ingress gateways not starting after chart upgrade

### ISSUE THREAD

**Issue by rrondeau** [hashicorp/consul-helm#971]
### Overview of the Issue

Consul ingress gateways not starting after helm upgrade with values

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  domain: "consul"
  datacenter: "dc1"
  image: "docker.io/consul:1.9.5"
  imageK8S: "docker.io/hashicorp/consul-k8s:0.25.0"
  imageEnvoy: "envoyproxy/envoy-alpine:v1.16.3"
  
....
....
  
connectInject:
  enabled: true
  healthChecks:
    enabled: false
  k8sAllowNamespaces: [........]
  centralConfig:
    enabled: true
  resources:
    requests:
      memory: "100Mi"
      cpu: "50m"
    limits:
      memory: "150Mi"
      cpu: "50m"

ingressGateways:
  enabled: true
  gateways:
    - name: front-ingress-gateway
    - name: back-ingress-gateway
  defaults:
    replicas: 2
    service:
      type: ClusterIP
      ports:
        - port: 8080
          nodePort: null
        - port: 8443
          nodePort: null
        - port: 9102
          nodePort: null
```
1. View error
```
consul-back-ingress-gateway-675659dd45-chmzf                  1/2     CrashLoopBackOff   13         30m
consul-front-ingress-gateway-79995bb7b4-87kmv                 1/2     CrashLoopBackOff   9          15m
```
### Logs

No logs from the container :/

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: 0.25.0
- `consul-helm` version: 0.31.1
- `envoy` version : 1.16.3

Additionally, please provide details regarding the Kubernetes Infrastructure, if known:
- Cloud Provider : GKE 1.19.9-gke.1400
- Networking CNI plugin in use: calico

### Additional Context

After some heavy debugging, the start command seems to be stuck when consul create a pipe to forward the boostrap config to envoy with `consul connect envoy ...`

To fix the issue i found a workaround, i replace the pod command from :
```
command:
  - /consul-bin/consul
  - connect 
  - envoy
  - -gateway=ingress
  - -proxy-id=$(POD_NAME)
  - -address=$(POD_IP):21000
```
to : 
```
command:
  - sh
  - -ec
  - |
    /consul-bin/consul connect envoy -gateway=ingress -proxy-id=$(POD_NAME) -address=$(POD_IP):21000 -bootstrap > /tmp/bootstrap.json
    /usr/local/bin/envoy --config-path /tmp/bootstrap.json --disable-hot-restart
```
If you have any hints, i will be happy to test anything
