### ISSUE TITLE
Which directory consul kv data is stored

### ISSUE THREAD

**Issue by oguzhanaygn** [hashicorp/consul-helm#978]
Hi, I've deployed consul with helm on my EKS v1.18 cluster. I'm using EFS storage driver to store consul server data created by users (especially kv). Everything looks fine, when I delete the nodes and pods and force to recreate themselves, key value datas are kept. To understand the concept of data storage of Consul, I mounted my EFS to normal EC2, I'm seeing 5 objects on each consul servers' access point:
```
acl-tokens.json
checkpoint-signature
node-id
raft/
serf/
```
and seems none of them are related  with kv data. When I create new kv, raft is getting bigger, but as far as I know, raft is related with leader election. I couldn't figure out kv data location even if Consul works fine right now. Any ideas about this situation?

My values.yaml:

```
global:
  enabled: true
  name: devops-consul
  domain: consul
  image: "hashicorp/consul:1.9.5"
  imageK8S: "hashicorp/consul-k8s:0.26.0-beta2"
  datacenter: xxx

  enablePodSecurityPolicies: true
  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
  tls:
    enabled: true
    enableAutoEncrypt: true
    serverAdditionalDNSSANs: ["xxx","yyy","zzz"]

    verify: true
    httpsOnly: false

  acls:
    manageSystemACLs: true

    bootstrapToken:
      # The name of the Kubernetes secret.
      secretName: null
      # The key of the Kubernetes secret.
      secretKey: null

server:
  enabled: true
  image: null
  replicas: 3
  bootstrapExpect: 3

  # Configures ports for the consul servers.
  ports:
    serflan:
      port: 8301
  storage: 10Gi
  storageClass: efs-sc
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"

  securityContext:
    runAsNonRoot: true
    runAsGroup: 1000
    runAsUser: 100
    fsGroup: 1000

  updatePartition: 0

  disruptionBudget:
    enabled: true
    maxUnavailable: 0

  extraConfig: |
    {
    "log_level": "INFO"
    }

  affinity: null

  priorityClassName: ""

  service:

    type: ClusterIP
    annotations: null

# Values that configure running a Consul client on Kubernetes nodes.
client:
  enabled: true
  image: "hashicorp/consul:1.9.5"
  join: null

  dataDirectoryHostPath: null

  grpc: false

  exposeGossipPorts: false

  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "50Mi"
      cpu: "50m"

  securityContext:
    runAsNonRoot: true
    runAsGroup: 1000
    runAsUser: 100
    fsGroup: 1000

  extraConfig: |
    {
    "log_level": "INFO"
    }

  dnsPolicy: ClusterFirst
  hostNetwork: false
  updateStrategy: |
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate

dns:
  enabled: true
  type: ClusterIP

# Values that configure the Consul UI.
ui:
  enabled: true
  service:
    enabled: false

```
