### ISSUE TITLE
Allow Consul client daemonset connectivity via nodePort (instead of only hostPort)

### ISSUE THREAD

**Issue by karras** [hashicorp/consul-helm#997]
#### Feature Description

Currently the Consul deployment on K8s relies on Kubernetes `hostPorts` to provide connectivity to the Consul clients as well as ensuring each app pod talks to its "K8s worker-local" Consul client. The design decision is well described in the Consul docs below:

* https://www.consul.io/docs/k8s/installation/install#client-agents

This causes various problems in organizations and environments where `hostPort` is not available, for example when running TKGI (previously known as PKS) < 1.11 or simply when security requirements do not allow you to use it.

Therefore we (@flavioaiello, @pree & @karras) investigated various scenarios how the Consul deployment could be adjusted to avoid the `hostPort` option. This would not only solve the problem but also improve security related requirements in certain environments.

We managed to successfully make the switch to `nodePorts` via 2-3 additional modifications:

* Adjust the K8s `--service-node-port-range` option to include the ports `8501` and `8502` (e.g. `8500-32767`)
* Activate the `ServiceTopology` feature gate (or `TopologyAwareHints` on K8s 1.21+)
* Create a `nodePort` service for the Consul clients with `topologyKeys` configured to avoid traffic loadbalancing and route everything to the local worker node (or `EndpointSlice` on K8s 1.21+)

**Note:** The adjustment of the `service-node-port-range` is only required due to the [hardcoded ports in consul-k8s](https://github.com/hashicorp/consul-k8s/blob/08cc8b62a359af12641bfa0bbcfc6d2473df6fe2/connect-inject/container_init.go#L264) and consul-helm. We'll track this in separate PRs. See also: https://github.com/hashicorp/consul-k8s/issues/544

Most likely making `nodePorts` the default deployment option would be desirable but I guess it's not possible because it would mean that every organization would need to enable the K8s feature gates. These are still in an alpha state and also disabled by default in vanilla K8s.

Additional references:

* https://kubernetes.io/docs/concepts/services-networking/service-topology/#only-node-local-endpoints
* https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/
* https://docs.pivotal.io/tkgi/1-11/release-notes.html

#### Use Case(s)

* Make it possible to deploy Consul in environments, organizations and K8s distributions where `hostPorts` are not an option
* Be closer aligned with K8s best practices

#### Contributions

We anticipate to open a PR soon with a new consul-helm flag/variable to allow this kind of deployment option.

**Comment by karras** [comment]
Working `nodePort` example service:
```
apiVersion: v1
kind: Service
metadata:
  name: consul-client
  namespace: consul
spec:
  type: NodePort
  selector:
    component: client
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 8501
  topologyKeys:
    - "kubernetes.io/hostname"
```

**Comment by pree** [comment]
Steps to get it running on Kubernetes `v1.21.1` using `TopologyAwareHints`:

- Activate FeatureGate `TopologyAwareHints` on `kube-apiserver`, `kube-controller` & `kube-proxy`.
- Label every node with a seperate zone: `kubectl label node <nodename> topology.kubernetes.io/zone=nodeX` (Zonename can be chosen freely, but every node needs to be a seperate zone)
- Create a `nodePort` service for the Consul clients with the annotation `service.kubernetes.io/topology-aware-hints: auto`

Working `nodePort` example service, tested on K8s (rancher) 1.21.1:
```
apiVersion: v1
kind: Service
metadata:
  name: consul-client
  namespace: consul
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  type: NodePort
  selector:
    component: client
  ports:
    - name: http 
      protocol: TCP
      port: 8501
      nodePort: 8501
      targetPort: 8501
    - name: grpc
      protocol: TCP
      port: 8502
      nodePort: 8502
      targetPort: 8502

```
